### ISSUE TITLE
The helm chart for IBM Cloud Object Storage comes configured for ICP by default

### ISSUE THREAD

**Issue by apetherick** [ibm-cloud-docs/containers#2467]
Following the instructions here

https://cloud.ibm.com/docs/containers?topic=containers-object_storage

The helm chart comes with values as below:
```
# ICP Configuration
provider: icp
```

```
# Datacenter name where cluster is deployed (required only for IKS)
dcname: ""
```

There should be a mention in the docs that this needs to be changed for IKS.

**Comment by Nadine2016** [comment]
@apetherick I can see that this is confusing, but if you want to install the Helm chart in an IBM Cloud Kubernetes Service cluster by following the instructions in the documentation, you install the `ibmc` Helm plug-in first. This plug-in will take care of all those settings, including the data center. So you actually do not have to change any values. Just install the `ibmc` plug-in. 

Let me know if this helps or if you have any other questions. Thank you

**Comment by Nadine2016** [comment]
closing. Feel free to reopen if you still experience any issues. thank you
