### ISSUE TITLE
Enable HTTP/2 protocol on ALB nginx ingress

### ISSUE THREAD

**Issue by bgehman** [ibm-cloud-docs/containers#2476]
Looking at docs here: https://cloud.ibm.com/docs/containers?topic=containers-ingress_annotation

I'm trying to figure out what annotation (if any) will enable nginx `http2` protocol support on the IKS ALB ingress.

Basically I want the alb nginx config to have:
```
server {
    listen 443 ssl http2;
    ...
```
instead of the default:
```
server {
    listen 443 ssl;
    ...
```

Background reading: https://www.nginx.com/blog/http2-module-nginx/

**Comment by Rachael-Graham** [comment]
Hi @bgehman, unfortunately HTTP2 is not supported in IKS. see https://cloud.ibm.com/docs/containers?topic=containers-limitations#classic_networking_limit
