### ISSUE TITLE
Feature Request - add whitelist-source-range 

### ISSUE THREAD

**Issue by msheeh17** [ibm-cloud-docs/containers#2477]
Hello
We have a need to restrict access to our public ingress in IBM Cloud and are looking too maintain those restrictions withiin the ingress via whitelist-source-range  which is available in nginx.ingress.kubernetes.io 

See: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#whitelist-source-range

**Comment by Rachael-Graham** [comment]
Hi @msheeh17 - I spoke with the dev team for ingress. There is currently no planned work for supporting this annotation. However you can use Calico network policies to restrict access to ALBs https://cloud.ibm.com/docs/containers?topic=containers-policy_tutorial#policy_tutorial

**Comment by Rachael-Graham** [comment]
Ah actually I got word of a workaround
You can use the location-snippets annotation like so:
```
  annotations:
    ingress.bluemix.net/location-snippets: |
      serviceName=<myservice1>
      # Example location snippet
      deny  192.168.1.1;
      allow 192.168.1.0/24;
      allow 10.1.1.0/16;
      allow 2001:0db8::/32;
      deny  all;
      <EOS>
```
This is based on the [nginx ngx_http_access_module](http://nginx.org/en/docs/http/ngx_http_access_module.html)

**Comment by msheeh17** [comment]
Oh this works perfectly, Thank you! Just what I needed.
