### ISSUE TITLE
helm init

### ISSUE THREAD

**Issue by bkoohi** [ibm-cloud-docs/containers#2479]
In instructions in this link:
https://cloud.ibm.com/docs/containers?topic=containers-helm#public_helm_install
helm init --service-account tiller 
is generating the following error
Error: unknown flag: --service-account

This seems not required step in helm v3:
https://github.com/helm/helm/issues/7052

**Comment by Rachael-Graham** [comment]
see https://github.com/ibm-cloud-docs/containers/issues/2482#issuecomment-585252925
