### ISSUE TITLE
helm repo

### ISSUE THREAD

**Issue by bkoohi** [ibm-cloud-docs/containers#2480]
In this link:
https://cloud.ibm.com/docs/containers?topic=containers-helm

For the following step and error:
helm repo add entitled https://raw.githubusercontent.com/IBM/charts/master/repo/entitled
Error: looks like "https://raw.githubusercontent.com/IBM/charts/master/repo/entitled" is not a valid chart repository or cannot be reached: Get https://raw.githubusercontent.com/IBM/charts/master/repo/entitled/index.yaml: dial tcp: lookup raw.githubusercontent.com: no such host

Please add the following step:
https://github.com/IBM/deploy-ibm-cloud-private/issues/80

**Comment by Rachael-Graham** [comment]
I wasnt able to replicate:
```
$ helm repo add entitled https://raw.githubusercontent.com/IBM/charts/master/repo/entitled
"entitled" has been added to your repositories
```

Which step from that deploy-ibm-cloud-private issue are you referring to?

**Comment by artberger** [comment]
The linked issue says to run:
`helm repo add stable https://raw.githubusercontent.com/IBM/charts/master/repo/stable`

Which is already in the doc topic, although we suggest naming it `ibm-charts` to match our UI. I also cannot replicate the entitled failure. I'm going to close this out here, but thanks for your contribution. Feel free to continue the conversation with us in Slack, in the [#docs public channel](https://ibm-cloud-success.slack.com/archives/C4G8V9GS1) if you're an external user, or if you're an IBMer, in the [internal channel](https://test.cloud.ibm.com/docs/containers?topic=containers-cs_internal#internal_help).
