### ISSUE TITLE
strongswan vpn

### ISSUE THREAD

**Issue by bkoohi** [ibm-cloud-docs/containers#2482]
This is 3rd issue I'm creating for this doc:
https://cloud.ibm.com/docs/containers?topic=containers-vpn#vpn_configure

Incorrect syntax:
 helm install -f config.yaml --name=vpn iks-charts/strongswan

Correct syntax is:
helm install vpn -f config.yaml iks-charts/strongswan

This is turning to a waste of time.....can somebody go through the doc and make sure steps and commands are correct????

**Comment by Rachael-Graham** [comment]
Hey @bkoohi , the commands on these pages were all using Helm v2 syntax. A few weeks ago we updated to use Helm v3 syntax. Closing this and your other issues; re-open if you see anything else.
