### ISSUE TITLE
IKS docs: Missing "Houston 02" in Single Zones for Classic Clusters

### ISSUE THREAD

**Issue by bgehman** [ibm-cloud-docs/containers#2488]
Docs located at: https://cloud.ibm.com/docs/containers?topic=containers-regions-and-zones#zones

In the table view, tab `Single Zones for Classic Clusters` -- the entry for `Houston 02` is missing...

Geography | Country | Metro | Data center|Deprecated region
-- | -- | -- | --|--
North America|United States|Houson|`hou02`|?

"Houston 02" shows as a valid option when ordering: https://cloud.ibm.com/kubernetes/catalog/cluster/create

**Comment by artberger** [comment]
@bgehman Thank you for raising this issue. `hou02` is the location where free clusters in US South are created, and not available to create a standard production cluster in. I have updated the docs accordingly, and it will go out with the next prod push.

**Comment by artberger** [comment]
This is in prod now, thanks again!

**Comment by bgehman** [comment]
Thanks @artberger  :+1:
