### ISSUE TITLE
Incorrect kubectl command 

### ISSUE THREAD

**Issue by ongkhaiwei** [ibm-cloud-docs/containers#2489]
On page - https://cloud.ibm.com/docs/containers?topic=containers-ingress-user_managed
 `kubectl get ingress-nginx -n kube-system `> Should be  `kubectl get service ingress-nginx -n kube-system`

**Comment by artberger** [comment]
Thank you, this is fixed in prod now. Going to close this out.

![image](https://user-images.githubusercontent.com/20074219/77592261-2fa3cd00-6ec8-11ea-9961-a1a8f629aca2.png)
