### ISSUE TITLE
ISS-sat-imagery-req

### ISSUE THREAD

**Issue by jacobIII** [ibm-cloud-docs/containers#2490]
It’s vital that this app gets approval from the I.S.S to use its satellite imagery.

**Comment by artberger** [comment]
@jacobIII, thanks for raising this issue. Unfortunately, the containers documentation squad cannot approve apps, but if you are having trouble setting up an app on IBM Cloud Kubernetes Service, please review the [troubleshooting documentation](https://cloud.ibm.com/docs/containers?topic=containers-cs_troubleshoot_app), reach out to your account manager, or [chat with us in Slack](https://cloud.ibm.com/kubernetes/slack).
