### ISSUE TITLE
Instructions for connection to etcd to verify KMS is incorrect

### ISSUE THREAD

**Issue by No9** [ibm-cloud-docs/containers#2493]
https://cloud.ibm.com/docs/containers?topic=containers-encryption#verify_kms 

Step 5 gives the following command:
```
etcdctl get /registry/secrets/default/<cluster_name> --endpoints <etcdEndpoints> --cacert="<etcdCACertFile>" --key="<etcdKeyFile>" --cert="<etcdCertFile>"
```
According to the kuberenetes docs it shouldn't be `<cluster_name>` but the name of a secret.
https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/#verifying-that-data-is-encrypted

**Comment by Rachael-Graham** [comment]
Thank you! We have verified & fixed this internally, and the fix will go to production today.
