### ISSUE TITLE
Devops Service - Jenkins X - Deprecated features in link

### ISSUE THREAD

**Issue by vincenthodicq** [ibm-cloud-docs/containers#2495]
Documentation linked to Jenkins X is from a blog spot of 2018 and is describing deprecated features of Jenkins X. For example regular Jenkins is deprecated and not used anymore. Jenkins X is now using tekton as pipelines engine.

If needed, I can assist for updating blog post.

**Comment by artberger** [comment]
@vincenthodicq thank you for raising this issue. Our doc team does not own the IBM Cloud blog, but we can pass along your feedback. Just to confirm, [this is the blog post you meant](https://www.ibm.com/cloud/blog/new-builders/installing-jenkins-x-on-ibm-cloud-kubernetes-service)?

If you mean the steps are outdated, you might try a PR into the samples repo: https://github.com/IBM-Cloud/kube-samples/tree/master/jenkins-x

**Comment by vincenthodicq** [comment]
@artberger Yes, i was talking about this article. I will look at the samples repo as colleagues were also working on installing / using JenkinsX on IKS.

**Comment by artberger** [comment]
Thanks, I passed along this feedback and will close out here.
