### ISSUE TITLE
Client IP Preservation Question

### ISSUE THREAD

**Issue by movinglightspeed** [ibm-cloud-docs/containers#2500]
https://cloud.ibm.com/docs/containers?topic=containers-vpc-lbaas#vpc_lb_dns
"Source IP preservation for requests is not supported in VPC."

However 
https://cloud.ibm.com/docs/vpc-on-classic-network?topic=vpc-on-classic-network-advanced-traffic-management#preserving-end-client-ip-address
states: for HTTP connection client IP preservation does happen. Can you clarify? Is the source IP Preservation not supported for IKS VPC Load balancer?

**Comment by Rachael-Graham** [comment]
Correct, in IKS the source IP automatically gets changed to the worker node ip that the request is forwarded to. This hop in the middle from where the request is forwarded from vpc lb to app pod, `vpc lb` -> `worker node ip` -> `app pod`, is where the source IP is not preserved. I am not sure if there is a timeline for when this will be enabled as an option for IKS
