### ISSUE TITLE
The default ks and cr plugins are not installing for ibmcloud cli on Win10

### ISSUE THREAD

**Issue by ajaychebbi** [ibm-cloud-docs/containers#2501]
I followed the instructions on the Access tab of my free cluster. It says run the command in powershell
```
Set-ExecutionPolicy Unrestricted; iex(New-Object Net.WebClient).DownloadString('http://ibm.biz/idt-win-installer')
```
I ran it in Powershell as a Administrator..  The documentation (https://cloud.ibm.com/docs/cli?topic=cloud-cli-getting-started#idt-prereq)  says that ks and cr plugins should be installed by default. but I don't see them installed.

```
PS C:\WINDOWS\system32> ibmcloud plugin list
Listing installed plug-ins...

Plugin Name                        Version   Status
cloud-functions/wsk/functions/fn   1.0.39
```

Also I am not able to manually install it 
```
PS C:\WINDOWS\system32> ibmcloud plugin install ks
Looking up 'ks' from repository 'IBM Cloud'...
FAILED
Plug-in 'ks' was not found on disk or in the repository 'IBM Cloud'.
Use 'C:\Program Files\IBM\Cloud\bin\ibmcloud.exe plugin repo-plugins -r 'IBM Cloud'' to list plugins available in the repo.
```

**Comment by Rachael-Graham** [comment]
Hmm, that is strange. I'll see if anything changed to remove those plugins recently.
You may have found them by now, but you can manually install them by running:
`ibmcloud plugin install kubernetes-service`
`ibmcloud plugin install container-registry`

**Comment by ajaychebbi** [comment]
@Rachael-Graham Thanks - yes I did find them by looking at the plugin catalog and install manually. For a first timer mapping `ks` to a plugin by the name `kubernetes-service` might be difficult if I am just following getting started instructions. Why it did not install by default is strange indeed.
