### ISSUE TITLE
Carbon 10 Card Link Styling Incorrect

### ISSUE THREAD

**Issue by tessarodes** [ibm-cloud-docs/containers#2504]
![image](https://user-images.githubusercontent.com/10426703/83573777-b6d97680-a4f1-11ea-9794-7966ef0eec13.png)

These cards should use or mimic [CloudPAL card styling](https://pages.github.ibm.com/ibmcloud/pal/components/card/usage), which has even 16px padding, no border (just a contrasting background color) a set few text heading sizes, and does not underline all text in the card. Ideally, the cards would be a fixed height across the row.

**Comment by artberger** [comment]
Discussed in Slack, and this is updated in prod now. Thanks for the issue, closing.

![image](https://user-images.githubusercontent.com/20074219/87820358-f3f88e80-c83b-11ea-9102-05caeca57e0a.png)
