### ISSUE TITLE
"classic" in not part of the nlb-dns command

### ISSUE THREAD

**Issue by psacchit** [ibm-cloud-docs/containers#2505]
ibmcloud ks nlb-dns add classic --cluster <cluster> --ip <load_balancer_IP> --nlb-host <Ingress_subdomain>

should be 
ibmcloud ks nlb-dns add --cluster <cluster> --ip <load_balancer_IP> --nlb-host <Ingress_subdomain>

Per 
https://cloud.ibm.com/docs/containers-cli-plugin?topic=containers-cli-plugin-kubernetes-service-cli#cs_nlb-dns-add

**Comment by artberger** [comment]
@psacchit thanks, I have made this change in our source repo, and the docs will be updated with the next prod push. I'm going to close this issue now, but let us know if you have any other feedback.
