### ISSUE TITLE
Change log for version 1.6 doesn't have information for 1.16.11_1536

### ISSUE THREAD

**Issue by conglinca** [ibm-cloud-docs/containers#2506]
I just updated my kubenette cluster worker node. Workers were updated to version `1.16.11_1536`.  However I couldn't find information of this version in change log.

**Comment by artberger** [comment]
Hi @conglinca it looks like the docs for this worker node update were published on 22 June 2020: https://cloud.ibm.com/docs/containers?topic=containers-changelog#11611_1536

Sometimes there is a bit of a delay between the time that an update becomes available and the time that the documentation is updated, but we try to do same-day publishing. Hope this helps, and thanks for your issue.
