### ISSUE TITLE
Prohibited term: master

### ISSUE THREAD

**Issue by cdmauney** [ibm-cloud-docs/containers#2508]
* https://cloud.ibm.com/docs/containers?topic=containers-cs_network_cluster
* https://cloud.ibm.com/docs/containers?topic=containers-cs_troubleshoot

Do not use. Use another term such as "controller," "leader," "parent," or "primary."

**Comment by artberger** [comment]
Hi @cdmauney , we are tracking this issue across a couple of our services [in this internal issue](https://github.ibm.com/alchemy-containers/documentation/issues/5756). Do you mind if I close this out here and continue working on that one? Or feel free to just reopen this!

**Comment by cdmauney** [comment]
@artberger Not at all. Thanks!
