### ISSUE TITLE
Missing reference to block storage plugin dependency

### ISSUE THREAD

**Issue by bennythejudge** [ibm-cloud-docs/containers#2509]
Hi,
this page https://cloud.ibm.com/docs/containers?topic=containers-cs_versions does not contain any reference to dependencies like for example the block storage plugin.
For example updating to Kube 1.15 with a storage plugin < 1.5.0 will prevent Kubernetes from attaching storage (from personal experience).
There should be at least a warning but ideally there should be a compatibility matrix with resources like the block storage plugin installed via `helm` (`ibmcloud-block-storage-plugin-x.y.z`).

**Comment by artberger** [comment]
Hi @bennythejudge thanks for your feedback. I'm not sure if the block storage plug-in is a dependency; I think that the plug-in is something optional that users choose to install in the cluster. To refer to compatibility of the Helm charts, you can look at the individual Helm chart to see the Kubernetes versions it supports. So for example, the [block storage plug-in Helm catalog](https://cloud.ibm.com/kubernetes/helm/iks-charts/ibmcloud-block-storage-plugin) entry, if you open the **Sources & Tar File** [link](https://icr.io/helm/iks-charts/charts/ibmcloud-block-storage-plugin-1.7.0.tgz), you can see the the `RELEASENOTES.MD` file that has a version history. I can update the docs with a note to check the compatibility of any plug-ins you use with the version you're updating to, and can also ask if we have any tool to make this process easier.
