### ISSUE TITLE
Copy to clipboard icon missing

### ISSUE THREAD

**Issue by xiepingp** [ibm-cloud-docs/containers#2510]
Commands should have a "copy to clipboard" icon next to them. Below pages have very many commands without the Copy to clipboard icon which is inconvenient for people who wants to copy these commands:
https://cloud.ibm.com/docs/containers?topic=containers-policy_tutorial
https://cloud.ibm.com/docs/containers?topic=containers-edge
https://cloud.ibm.com/docs/containers?topic=containers-cs_network_cluster
https://cloud.ibm.com/docs/containers?topic=containers-app
https://cloud.ibm.com/docs/containers?topic=containers-serverless-apps-knative
https://cloud.ibm.com/docs/containers?topic=containers-vpc-block
https://cloud.ibm.com/docs/containers?topic=containers-service-binding
https://cloud.ibm.com/docs/containers?topic=containers-cs_troubleshoot
https://cloud.ibm.com/docs/containers?topic=containers-cs_troubleshoot_clusters

Screenshots please refer to below:
![K5 no Copy button 18](https://user-images.githubusercontent.com/63960906/88363102-75f33500-cdb1-11ea-8725-9d57b6de776b.png)
![K5 no Copy button 19](https://user-images.githubusercontent.com/63960906/88363118-89060500-cdb1-11ea-9506-2de4e24b8e6c.png)
![K5 no Copy button 20](https://user-images.githubusercontent.com/63960906/88363119-8a373200-cdb1-11ea-9222-9abeabab87ec.png)
![K5 no Copy button 21](https://user-images.githubusercontent.com/63960906/88363121-8acfc880-cdb1-11ea-8bdb-1feb0efb1c74.png)
![K5 no Copy button 22](https://user-images.githubusercontent.com/63960906/88363127-8c00f580-cdb1-11ea-83b8-777ba0b4816d.png)
![K5 no Copy button 23](https://user-images.githubusercontent.com/63960906/88363128-8c998c00-cdb1-11ea-860a-5513a831d94e.png)
![K5 no Copy button 24](https://user-images.githubusercontent.com/63960906/88363129-8e634f80-cdb1-11ea-87e7-8e8feabe54fd.png)
![K5 no Copy button 25](https://user-images.githubusercontent.com/63960906/88363130-8efbe600-cdb1-11ea-8e3b-24cbe6ff6988.png)
![K5 no Copy button 26](https://user-images.githubusercontent.com/63960906/88363132-8f947c80-cdb1-11ea-9af9-5d335c99fb58.png)
![K5 no Copy button 27](https://user-images.githubusercontent.com/63960906/88363135-902d1300-cdb1-11ea-9439-17d8513f1b6c.png)
![K5 no Copy button 28  ](https://user-images.githubusercontent.com/63960906/88363139-90c5a980-cdb1-11ea-9eb3-b940adc12ff9.png)
![K5 no Copy button 29](https://user-images.githubusercontent.com/63960906/88363143-91f6d680-cdb1-11ea-9d75-643a7b9a7c20.png)
![K5 no Copy button 30](https://user-images.githubusercontent.com/63960906/88363144-928f6d00-cdb1-11ea-8e8a-59c4e3a266eb.png)

**Comment by artberger** [comment]
Thanks @xiepingp for this feedback. I have updated the docs and believe these are fixed. Closing.

**Comment by xiepingp** [comment]
@artberger Thanks for the fixing!
