### ISSUE TITLE
Link for plug in not working

### ISSUE THREAD

**Issue by SiWafer** [ibm-cloud-docs/containers#2513]
In the body there is a link for a plug in that does not work

`Classic clusters:`

`Install the {{site.data.keyword.cloud_notm}} Block Volume Attacher plug-in.
To add block storage with a different configuration, add block storage to a subset of worker nodes only, or to have more control over the provisioning process, manually add block storage. For highly available data storage, Portworx requires at least 3 worker nodes with raw and unformatted block storage.
Attach the block storage to your worker nodes.
Continue with your Portworx setup by Setting up a key-value store for Portworx metadata.`

**Comment by artberger** [comment]
Hello @SiWafer , thanks for opening this issue. I believe this link now works: https://cloud.ibm.com/docs/containers?topic=containers-utilities#manual_block

Let me know if you have other feedback, thanks!
