### ISSUE TITLE
correct command parameters

### ISSUE THREAD

**Issue by abkumarggn** [ibm-cloud-docs/containers#2514]
In the bottom of this page, please correct the helm release name to correct name 

current version:

`helm uninstall ibm-ks-cluster-autoscaler -n <namespace>`

correct version:

`helm uninstall ibm-iks-cluster-autoscaler -n <namespace>`

**Comment by derekpoindexter** [comment]
@abkumarggn Thanks for your feedback. I've made the change upstream. It will go out with next update.
