### ISSUE TITLE
nginx-ingress-controller version

### ISSUE THREAD

**Issue by psacchit** [ibm-cloud-docs/containers#2515]
the newest version of nginx-ingress-controller is 0.34.1
The arguments are now different.
Following these docs result in failures in VPC Gen 2 clusters.

**Comment by Rachael-Graham** [comment]
Hi there, which doc page are you referring to?

**Comment by psacchit** [comment]
The mandatory.yaml file...
 
https://cloud.ibm.com/docs/containers?topic=containers-ingress-user_managed#user_managed_nlb
 
Is really out of date.
 
Phil SacchitellaBlockchain ArchitectIBM Corporation585-489-8687psacchit@us.ibm.com
 
 
----- Original message -----From: Rachael Graham <notifications@github.com>To: ibm-cloud-docs/containers <containers@noreply.github.com>Cc: Phil Sacchitella <psacchit@us.ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [ibm-cloud-docs/containers] nginx-ingress-controller version (#2515)Date: Mon, Aug 17, 2020 1:39 PM 
 
Hi there, which doc page are you referring to?

**Comment by artberger** [comment]
Thank you @psacchit , we updated the doc to this link: https://github.com/kubernetes/ingress-nginx/blob/master/deploy/static/provider/cloud/deploy.yaml

and it should go out with the next prod push.
