### ISSUE TITLE
Step: Setting up a Load Balancer for VPC, p. 5 lists an invalid command 

### ISSUE THREAD

**Issue by vladimiratanasov** [ibm-cloud-docs/containers#2516]
EDIT: I found out the command is part of the vpc-infrastructure/infrastructure-service plugin. I will leave the ticket open for posterity. Please feel free to close it if you decide no action is required 

Point 5 in the mentioned step lists the command `ibmcloud is load-balancers`, but no such command exists

https://cloud.ibm.com/docs/containers?topic=containers-vpc-lbaas#setup_vpc_ks_vpc_lb

**Comment by Rachael-Graham** [comment]
I think this is a good point to mention in the docs - add the plugin in the "before you begin" prerequisites, or make this step optional for those who have the plugin and want to run it. I'll change the upstream source and close whenever the changes make it to production. Thank you!
