### ISSUE TITLE
YAML for BYOK Encyption Secret is incorrectly formatted 

### ISSUE THREAD

**Issue by sethmccombs** [ibm-cloud-docs/containers#2520]
When you look at the docs page as rendered - the YAML is incorrectly formatted and copies incorrectly - 
<img width="785" alt="Screen Shot 2020-09-16 at 12 32 39 PM" src="https://user-images.githubusercontent.com/5605413/93383885-1fd2c900-f819-11ea-96e1-ac5347ead5fd.png">

But looking at the `raw`, it appears incorrectly formatted? 

<img width="1628" alt="Screen Shot 2020-09-16 at 12 32 45 PM" src="https://user-images.githubusercontent.com/5605413/93383959-3e38c480-f819-11ea-9792-6d89223e51a8.png">

I don't know enough about the rendering/formatting engine that IBM's docs use to open a PR for this fix

**Comment by artberger** [comment]
Thanks for raising this issue. I believe it was an indentation error that I have fixed in our source repo. The updates will go out with our next prod push (probably later today). Closing.
