### ISSUE TITLE
TLS Passthrough

### ISSUE THREAD

**Issue by wrridgwa** [ibm-cloud-docs/containers#2526]
With either Classic Cluster or a VPC cluster, do they support passing TLS connections through the ALB to allow the backend pod to decrypt the connection? It seems like all of the options require a Certificate/Secret to be on the ALB to allow decryption at the ALB.

**Comment by Rachael-Graham** [comment]
You can check out the TCP ports annotation to have the ALb operate in pass-through mode: https://cloud.ibm.com/docs/containers?topic=containers-ingress_annotation#tcp-ports Reopen if you have more questions or suggestions!
