### ISSUE TITLE
Values do not match examples in Accessing Kubernetes clusters

### ISSUE THREAD

**Issue by bennythejudge** [ibm-cloud-docs/containers#2528]
In https://cloud.ibm.com/docs/containers?topic=containers-access_cluster#access_private_se there is reference to a port `30426`  but this port is not shown anywhere in the previous code

```
Edit your Kubernetes configuration file to add the word private to the service endpoint URL. For example, in the Kubernetes configuration file kube-config-prod-dal10-mycluster.yml, the server field might look like server: https://c1.us-east.containers.cloud.ibm.com:30426. You can change this URL to the private service endpoint URL by changing the server field to server: https://c1.private.us-east.containers.cloud.ibm.com:30426.
```

It would be nice if all the code was based on an actual run of the procedure

**Comment by Rachael-Graham** [comment]
Hi there - This is just an example of a nodeport that your cluster wont actually use. I can change it to `<nodeport>` to make it clearer. Thank you!
