### ISSUE TITLE
Remove Beta statements from IKS Kubernetes Ingress controller documentation

### ISSUE THREAD

**Issue by renevandalen** [ibm-cloud-docs/containers#2530]
On the following documentation pages it states that the Kubernetes Ingress controller is BETA:
https://cloud.ibm.com/docs/containers?topic=containers-ingress-types
https://cloud.ibm.com/docs/containers?topic=containers-comm-ingress-annotations

while on the https://cloud.ibm.com/kubernetes/clusters page it states that this is now supported and all should migrate before EoS of the legacy service:

```
The Kubernetes Ingress controller image is now supported for Ingress ALBs, and all new ALBs now run the Kubernetes Ingress image by default. Additionally, you must move any existing Ingress setups to the new Kubernetes Ingress before support for the legacy IBM Cloud Kubernetes Service Ingress image ends on April 30, 2021. More info: https://ibm.biz/kube-ingress
```

Shouldn't the BETA statements be removed from the documentation if this is the recommended configuration on the Clusters page in the IBM Cloud Portal ?

**Comment by Rachael-Graham** [comment]
Went GA officially [02 Nov](https://cloud.ibm.com/docs/containers?topic=containers-iks-release#nov20), removed beta statements then. Thank you!
