### ISSUE TITLE
--docker-username and --docker-password confusion

### ISSUE THREAD

**Issue by ssiegel95** [ibm-cloud-docs/containers#2531]
Concerning `--docker-username` and `--docker-password`

For step 6 of [this](https://cloud.ibm.com/docs/containers?topic=containers-registry#other_registry_accounts) section it was very unclear to me whether I should use different values for these fields. 

The docs state:

--docker-username iamapikey | Required. Enter the username to log in to your private registry. For IBM Cloud Container Registry, the username is set to the value iamapikey.
-- | --
--docker-password <token_value> | Required. Enter the value of your API Key that you previously retrieved.

For `--docker-password` it seems obvious that you are referring to the output API Key from step 4. However for `--docker-username` what is the "imapikey". is it the same value? I've tried that and the pull secret end up not working so the answer is probably 'no'.

**Comment by Rachael-Graham** [comment]
Hi there - 
If you’re using ICR, you can just enter `iamapikey` as the username.
If you're creating this secret for some other registry, you might have a diff username for that registry

I can update this doc to make that wording a bit cleaner
