### ISSUE TITLE
Enable CRL with mutual-auth annotation on ALB nginx ingress

### ISSUE THREAD

**Issue by malek0512** [ibm-cloud-docs/containers#2532]
Looking at docs here: https://github.com/ibm-cloud-docs/containers/blob/master/cs_annotations.md#mutual-auth

I'm trying to figure out what annotation (if any) will enable CRL support on the IKS ALB ingress.
Basically I want the alb nginx config to have:

    ssl_crl <file>;

**Comment by Rachael-Graham** [comment]
So if you're using the regular IKS ingress alb then I dont think this is supported. if you switch to the new Kubernetes-based ingress controller (https://cloud.ibm.com/docs/containers?topic=containers-ingress-types) then it looks like you can: https://kubernetes.github.io/ingress-nginx/examples/auth/client-certs/

**Comment by malek0512** [comment]
@Rachael-Graham Thank you for your response. That spared me few hours of digging
