### ISSUE TITLE
kubectl command promting the password for openshfit cluster

### ISSUE THREAD

**Issue by ramachittala** [ibm-cloud-docs/containers#2536]
$ ibmcloud login --api @file 
$ ibmcloud ks cluster ls
$ ibmcloud ks cluster config --cluster <clustername>
$ kubectl config current-context

Still it was asking the password while running the kubectl commands. Please help. 
I tried in both my local and ibm cloud shell as well.

**Comment by artberger** [comment]
@ramachittala for OpenShift clusters, can you try either setting the context as an admin (`ibmcloud ks cluster config -c <cluster> --admin` or using the OpenShift web console to log in? A couple other options are documented here: https://cloud.ibm.com/docs/openshift?topic=openshift-access_cluster#access_public_se

**Comment by Rachael-Graham** [comment]
Closing for staleness. Re-open if this is still an issue.
