### ISSUE TITLE
gRPC support on ALB nginx ingress

### ISSUE THREAD

**Issue by bhairavi25** [ibm-cloud-docs/containers#2538]
Hello,

I'm trying to figure out what annotation (if any) will enable gRPC on the IKS ALB ingress. Referring the docs in here: https://cloud.ibm.com/docs/containers?topic=containers-ingress_annotation

Basically I want the alb nginx config like this:
```
server {
    ....
    ....

    location ^~ /sample.SampleService {
      grpc_pass grpc://host:port;
      ...
     }
}
```

Background reading: https://www.nginx.com/blog/nginx-1-13-10-grpc/

Thanks in advance!

**Comment by Rachael-Graham** [comment]
if you're using the custom IKS ingress image ^^then gRPC is not supported.
you can use grpc w the newly-supported community k8s image if you want to migrate: https://cloud.ibm.com/docs/containers?topic=containers-ingress-types#alb-image-diff
