### ISSUE TITLE
The Link : "Maersk and IBM formed a joint venture" points to our SLA

### ISSUE THREAD

**Issue by LarsIpsen** [ibm-cloud-docs/containers#2539]
on the page : https://cloud.ibm.com/docs/containers?topic=containers-cs_uc_transport#uc_shipping
There is a link :  "Maersk and IBM formed a joint venture", it points to our SLA web site andnot to the use case description. 
I guess the link should have point to : https://www-03.ibm.com/press/us/en/pressrelease/53602.wss#:~:text=Moller%20%E2%80%93%20Maersk%20(MAERSKb.CO,global%20trade%20using%20blockchain%20technology.

**Comment by artberger** [comment]
Thanks @LarsIpsen , I have updated the link in our source doc, and the change will go out with the next doc prod push. I'm going to close this issue here.
