### ISSUE TITLE
The step to obtain crn details of a certificate is missing 

### ISSUE THREAD

**Issue by abhishektuf** [ibm-cloud-docs/containers#2540]
Hi Team, the command to obtain the crn details of the existing certificate that customer wants to copy is missing from the document here. Please add the below command & step to the document.

https://cloud.ibm.com/docs/containers?topic=containers-ingress-types#manage_certs

To obtain the crn of the certificate you want to copy run the below command:
ibmcloud ks ingress secret ls -c <Cluster name or ID>
This command will list all the certificates with their crn details used in the cluster.

**Comment by Rachael-Graham** [comment]
Adding upstream and will be published in production soon! Thank you
