### ISSUE TITLE
Tutorials using Konveyor Move2Kube

### ISSUE THREAD

**Issue by ashokponkumar** [ibm-cloud-docs/containers#2541]
We are looking to host the below tutorials in IBM Cloud website too. Please let us know how to take it further.

https://konveyor.io/move2kube/docs/tutorial

[Migrating Docker compose/swarm apps to Kubernetes](https://konveyor.io/move2kube/tutorials/docker-compose/)
[Migrating VM apps to Kubernetes](https://konveyor.io/move2kube/tutorials/language-platforms/)
[Migrating Cloud Foundry apps to Kubernetes](https://konveyor.io/move2kube/tutorials/cloud-foundry/)
[Using Move2Kube UI](https://konveyor.io/move2kube/tutorials/move2kube-ui/)

**Comment by artberger** [comment]
Discussing in Slack to make sure I understand the request. Thanks for your comment.

**Comment by Rachael-Graham** [comment]
Discussion in slack. Re-open if needed.
