### ISSUE TITLE
Section regarding community controller needs update

### ISSUE THREAD

**Issue by xzlin** [ibm-cloud-docs/containers#2546]
In https://cloud.ibm.com/docs/containers?topic=containers-ingress-user_managed#user_managed_nlb, step 1, mandatory.yaml needs to be deploy.yaml. app.kubernetes.io/part-of: ingress-nginx needs to be app.kubernetes.io/instance: ingress-nginx

**Comment by Rachael-Graham** [comment]
Thank you, this page was outdated. Updated in our upstream files and will be pushed to the production documentation soon!
