### ISSUE TITLE
YAML file for the ingress v1 is not valid

### ISSUE THREAD

**Issue by LarsIpsen** [ibm-cloud-docs/containers#2547]
The YAML example in the step 2 of https://cloud.ibm.com/docs/containers?topic=containers-ingress-types#alb-comm-create
is not valid if you use v1 (kube 1.19)
See defintion https://kubernetes.io/docs/concepts/services-networking/ingress/

**Comment by Rachael-Graham** [comment]
Thanks, updated for a 1.19 option!
