### ISSUE TITLE
GPU bare metal worker nodes not available on OpenShift clusters

### ISSUE THREAD

**Issue by vfandino** [ibm-cloud-docs/containers#2548]
When comparing between OpenShift and community Kubernetes clusters (https://cloud.ibm.com/docs/containers?topic=containers-cs_ov), seems that GPU bare metal worker nodes are not available on OpenShift. However, you can select them when creating and OpenShift cluster, and they are listed in the About page of the service (https://cloud.ibm.com/kubernetes/catalog/about?platformType=openshift)

Thank you

**Comment by Rachael-Graham** [comment]
Thank you! This page was outdated. It has been updated upstream and will be published in production shortly.
