### ISSUE TITLE
Secondary storage availability supported on VPC clusters is not clear

### ISSUE THREAD

**Issue by vfandino** [ibm-cloud-docs/containers#2549]
Based on this page (https://cloud.ibm.com/docs/containers?topic=containers-storage_planning#non_persistent_overview), seems that both primary and secondary storage are available in VPC worker nodes for non-persistent storage. However, having a look at the Storage entry in the Classic vs VPC comparision (https://cloud.ibm.com/docs/containers?topic=containers-infrastructure_providers), you can read that, for non-persistent storage, secondary storage on the local worker node is not available in VPC.

Thank you

**Comment by artberger** [comment]
@vfandino thank you for opening this issue. I have remove VPC from that non-persistent storage table, and the doc will be updated with the next prod push. I'm going to close this issue.
