### ISSUE TITLE
A part of the text is very complex to understand

### ISSUE THREAD

**Issue by LarsIpsen** [ibm-cloud-docs/containers#2550]
In the section : https://cloud.ibm.com/docs/containers?topic=containers-ingress-types#verifying-permissions-for-certificate-manager
The paragraphs:
`For a Certificate Manager instance to be created for your new or existing cluster, ensure that the API key for the region and resource group that the cluster is created in has the correct permissions.

If the account owner set the API key, then your cluster is assigned a Certificate Manager instance.
If another user or a functional ID set the API key, first assign the user the Administrator .....`
Is very complex to understand, I guess there are missing some wordering, and we should explain where to find info about the API keys

**Comment by Rachael-Graham** [comment]
Thanks Lars, I added a step for how to check the api key for the cluster first. Updated in upstream and will be pushed to production docs shortly.
