### ISSUE TITLE
Guidance to import custom TLS certificate isn't correct

### ISSUE THREAD

**Issue by LarsIpsen** [ibm-cloud-docs/containers#2551]
In the step 3 in the section : https://cloud.ibm.com/docs/containers?topic=containers-ingress-types#manage_certs_custom
We inform, that you can get the CRN of the certificate by the command : `You can find the certificate CRN by running ibmcloud ks ingress secret ls -c <cluster_name_or_ID>.`
That is not correct.... it is only correct if you already have imported the certificate.... First time you need to get the certificate CRN from the Cert manager, you can get it from the UI and probably also from a CLI command.

**Comment by Rachael-Graham** [comment]
Yes, you are right, that's a bit of putting the carriage before the horse. Updated in upstream docs and will push to production shortly.
