### ISSUE TITLE
Specify type of tier for VM

### ISSUE THREAD

**Issue by vfandino** [ibm-cloud-docs/containers#2552]
The cost of worker nodes based on virtual machines is tiered. It is not clear if it is a simple or graduated tier.

Thank you very much

https://cloud.ibm.com/docs/containers?topic=containers-costs

**Comment by Rachael-Graham** [comment]
Hello- sorry for getting to this issue late! The tiers are graduated. We've updated the docs upstream and will push the update to production docs shortly. Thank you!
