### ISSUE TITLE
Inbound/Outbound destination and source port rules are incorrect/misleading

### ISSUE THREAD

**Issue by gtstark07** [ibm-cloud-docs/containers#2554]
Document: https://cloud.ibm.com/docs/containers?topic=containers-vpc-network-policy#acls_ui 

After testing in a Gen2 VPC/IKS cluster via curl, in order to open Inbound https traffic, the destination port exception must be set to 443.

Likewise, the Outbound rule should set Source port exception to 443. 

The table in the above document does not reflect this behavior - it is reversed (along with a note saying it only applies to gen1 VPC when that is apparently not the case.)

**Comment by Rachael-Graham** [comment]
Hi there - sorry for getting to this issue late! We've tested these ACL rules extensively and so far haven't found this to be the case. However I will sit down w the network squad next week to take a look. Will update accordingly!

**Comment by gtstark07** [comment]
Hi,

Any update on your findings?

**Comment by Rachael-Graham** [comment]
I believe you're right in that ACLs are applied to the LBaaS, considering that it sits on one of the subnets in your account. I'm updating the docs upstream to reflect the 443 rule, and will push the changes to production in the next few days. Thank you!
