### ISSUE TITLE
Remove reference to Blog Beta

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/containers#2555]
Please remove to a blog from 2018 about Beta Storage unless this is still relevant

```
If your app is a StatefulSet that requires local storage, you can use SDS machines and provision Kubernetes local persistent volumes (beta)
```

https://cloud.ibm.com/docs/containers?topic=containers-planning_worker_nodes

**Comment by Rachael-Graham** [comment]
Thank you, updated in upstream and will be pushed to production docs shortly!
