### ISSUE TITLE
ibmcloud CLI create classic Kubernetes cluster --flavor parameter is deprecated

### ISSUE THREAD

**Issue by Gaurav-Ramakrishna** [ibm-cloud-docs/containers#2557]
ibmcloud CLI create classic Kubernetes cluster **--flavor** parameter is deprecated and replaced by **--machine-type**. But the [documentation](https://cloud.ibm.com/docs/containers?topic=containers-clusters#clusters_standard) still shows **--flavor** and is not updated.

**Comment by Rachael-Graham** [comment]
Hello, the opposite is true - the machine-types flag was replaced with the flavor flag in version 0.4.90. Let me know if the flavor flag does not work for you.
