### ISSUE TITLE
Client request body size doc section fix

### ISSUE THREAD

**Issue by admgolovin** [ibm-cloud-docs/containers#2559]
The Client request body size section doesn't contain information about the way of configuring this setting through the annotation labels of the ingress resource for the new Ingress controller based on community Nginx. 
But the Nginx ingress docs describe the annotation label which makes it possible to configure this setting: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#proxy-buffer-size
I've verified that the Nginx ingress suggested annotation label is working. So could you please add that label description to the docs?

Other annotation label descriptions contain the `Kubernetes Ingress field:` field that describes the annotation label config snippet for the community Nginx ingress controller version. 
And for this section it is missed: 
```
Client request body size
Set the maximum size of the body that the client can send as part of a request.

Previous IBM Cloud Kubernetes Service Ingress resource annotations:

ingress.bluemix.net/client-max-body-size: "serviceName=app1 size=200m"
Kubernetes ibm-k8s-controller-config configmap field:

proxy-body-size: 200m
```

This is confusing and makes you think that the annotation label approach is not supported in this particular case.

**Comment by Rachael-Graham** [comment]
Thanks for the issue! Yes, the annotation is supported, but i think you will want this one https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size (instead of buffer size). I've added it to the upstream docs and will push this change to production shortly.
