### ISSUE TITLE
Remove wording in Setting up Kubernetes Ingress topic

### ISSUE THREAD

**Issue by alaaalii** [ibm-cloud-docs/containers#2560]
In this topic: https://cloud.ibm.com/docs/containers?topic=containers-ingress-types there is a sentence that reads:

>Support for the custom IBM Ingress image ends in 6 months on 30 April 2021.

This means this statement needs to be changed every month. We can simply remove the `in 6 months` part and have it state the date:

>Support for the custom IBM Ingress image ends on 30 April 2021.

This sentence occurs twice in the doc.

**Comment by Rachael-Graham** [comment]
Thanks, updated upstream and will be pushed to production shortly!
