### ISSUE TITLE
Debug / Verbose logging on IKS community ingress nginx controller 

### ISSUE THREAD

**Issue by bhairavi25** [ibm-cloud-docs/containers#2563]
Hello,

I am trying to enable debug/verbose logging in the IKS community ingress nginx controller. From the IBM docs see that we can customize deployment but don't find details on how to configure debug logging

https://cloud.ibm.com/docs/containers?topic=containers-comm-ingress-annotations#annotations

In the community ingress nginx controller this can be done by adding the flag as container args `--v=5`

example below:

```
template:
   ....
   ....
   spec:
      containers:
      - args:
        - /nginx-ingress-controller
        - --default-backend-service=default/dash-ingress-nginx-ingress-default-backend
        - --election-id=ingress-controller-leader
       ....
       .... 
        - --enable-ssl-passthrough
        - --v=5 #enables debug log 
```

For more details: https://kubernetes.github.io/ingress-nginx/troubleshooting/#debug-logging

**Comment by Rachael-Graham** [comment]
Hi there - Currently there's not a way to do this with the `ibm-ingress-deploy-config` configmap doe the customizable deployment, but it is something I request of the dev team. I've put in an issue for them and can keep you updated.

**Comment by Rachael-Graham** [comment]
In the meantime, you may be able to use: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#error-log-level
