### ISSUE TITLE
Confusing k8s+cluster-autoscaler version information

### ISSUE THREAD

**Issue by qrilka** [ibm-cloud-docs/containers#2568]
For version 1.20 of Kubernetes the page https://cloud.ibm.com/docs/containers?topic=containers-cs_versions#cs_v120 says

> Before you update your cluster, check that you do not need the cluster autoscaler add-on, which is not supported in Kubernetes 1.20.

As the same time cluster-autoscaler addon changelog page https://cloud.ibm.com/docs/containers?topic=containers-ca_changelog says "Kubernetes 1.15.0 - < 1.20.0" (probably "- <" means "≤") and "1.17 - 1.20" as supported versions

**Comment by qrilka** [comment]
BTW IBM Cloud CLI also shows version 1.0.2 supporting 1.20:
```
$ ic ks addon-versions --addon cluster-autoscaler
OK
Name                 Version           Supported Kubernetes Range   Supported Openshift Range   
cluster-autoscaler   1.0.1             >=1.15.0 <1.20.0             >=4.3.0   
cluster-autoscaler   1.0.2 (default)   >=1.17.0 <1.21.0             >=4.3.0 
```

**Comment by derekpoindexter** [comment]
Thanks for the feedback, I've updated the doc here - https://cloud.ibm.com/docs/containers?topic=containers-ca_changelog
