### ISSUE TITLE
Inbound and Outbound rules for ports 30000-32767, 

### ISSUE THREAD

**Issue by kevinbarker1960** [ibm-cloud-docs/containers#2572]
Opened a case with a question.
https://cloud.ibm.com/unifiedsupport/cases?accountId=70372f6f08e74b819ef67e5ea8d5084d&number=CS2344930

The response was to have me open an issue and refer to the case.

https://cloud.ibm.com/docs/containers?topic=containers-vpc-network-policy#acls_ui
has rules for inbound and outbound regarding:
INBOUND:
Allow incoming traffic requests to apps that run on your worker nodes. 	Allow 	TCP 	Any 	30000 - 32767 	Any 	- 	After 3
OUTBOUND:
Allow incoming traffic requests to apps that run on your worker nodes. 	Allow 	TCP 	Any 	30000 - 32767 	Any 	- 	After 3

And CLI for the above:
ibmcloud is network-acl-rule-add $acl_id allow outbound tcp 0.0.0.0/0 0.0.0.0/0 --name allow-ingress-outbound --destination-port-min 30000 --destination-port-max 32767
ibmcloud is network-acl-rule-add $acl_id allow inbound tcp 0.0.0.0/0 0.0.0.0/0 --name allow-ingress-inbound --destination-port-min 30000 --destination-port-max 32767

Using my own acl_id, the result was:
ibmcloud is network-acl-rule-add $acl_id allow outbound tcp 0.0.0.0/0 0.0.0.0/0 --name allow-ingress-outbound --destination-port-min 30000 --destination-port-max 32767
Adding rule for network ACL r006-... under account IBM WH VPC Development as user kbarker@us.ibm.com...

ID                     ...
Name                   allow-ingress-outbound
Direction              outbound
Action                 allow
IP version             ipv4
Source                 0.0.0.0/0
Destination            0.0.0.0/0
Protocol               tcp
Min source port        1
Max source port        65535
Min destination port   30000
Max destination port   32767
[root@47f27773e438 function]# ibmcloud is network-acl-rule-add $acl_id allow inbound tcp 0.0.0.0/0 0.0.0.0/0 --name allow-ingress-inbound --destination-port-min 30000 --destination-port-max 32767
Adding rule for network ACL r006-e39563b3-e36a-4fa6-86d6-5cc6aa22d271 under account IBM WH VPC Development as user kbarker@us.ibm.com...

ID                     ...
Name                   allow-ingress-inbound
Direction              inbound
Action                 allow
IP version             ipv4
Source                 0.0.0.0/0
Destination            0.0.0.0/0
Protocol               tcp
Min source port        1
Max source port        65535
Min destination port   30000
Max destination port   32767

I have been told by those using the systems with the above that it does not work, the OUTBOUND flow needs to have the source and destination flipped.
For example, we have rules to open up port 443, to get it to work we had to use source and destination flipped between inbound and outbound:

ibmcloud is network-acl $acl_id
Rules

inbound
...Action   IP version   Protocol                                                     Source               Destination
...allow    ipv4              tcp                                                              0.0.0.0/0            0.0.0.0/0
                                       Source ports: Min=1,Max=65535
                                      Destination ports: Min=443,Max=443

outbound
...Action   IP version   Protocol                                                    Source            Destination
...allow    ipv4         tcp                                                                  0.0.0.0/0         0.0.0.0/0
                                  Source ports: Min=443,Max=443
                                  Destination ports: Min=1,Max=65535

Would like to verify that the documentation is correct. Or if the documentation needs to be updated for the outbound flow.  I am being told the documentation is wrong.

The way is seems like is should be is  (the following is from a terraform plan log):
          rules {
              action      = "allow"
              destination = "0.0.0.0/0"
              direction   = "inbound"
              id          = "..."
              ip_version  = "ipv4"
              name        = "tcp-in-traffic-ports-kube-origin"
              source      = "0.0.0.0/0"
              subnets     = 3
  
              tcp {
                  port_max        = 65535
                  port_min        = 1
                  source_port_max = 32767
                  source_port_min = 30000
              }
          }
          rules {
              action      = "allow"
              destination = "0.0.0.0/0"
              direction   = "outbound"
              id          = "..."
              ip_version  = "ipv4"
              name        = "tcp-out-traffic-ports-kube"
              source      = "0.0.0.0/0"
              subnets     = 3
  
              tcp {
                  port_max        = 32767
                  port_min        = 30000
                  source_port_max = 65535
                  source_port_min = 1
              }
          }

The pattern used for 443 what we were excepting to see where the ports are flipped between in and out like in the terraform above.

**Comment by Rachael-Graham** [comment]
The [console steps](https://cloud.ibm.com/docs/containers?topic=containers-vpc-network-policy#acls_ui) and [CLI steps](https://cloud.ibm.com/docs/containers?topic=containers-vpc-network-policy#acls_cli) have been updated. In particular I believe the directionality of the ports was incorrect, so that has been updated. I will close this issue, but please re-open if you are still having issues or have other questions!
