### ISSUE TITLE
COMMAND DOES NOT WORK

### ISSUE THREAD

**Issue by cniemi** [ibm-cloud-docs/containers#2573]
ibmcloud ks ingress status -c <cluster_name_or_ID>

ingress does not work? 

"'ingress' is not a registered command. See 'ibmcloud cs help'."

**Comment by derekpoindexter** [comment]
Thanks for the feedback.
- Make sure you update your CLI - https://cloud.ibm.com/docs/cli?topic=cli-install-ibmcloud-cli#update-ibmcloud-cli
- And that you pass the correct parameter for the `ks ingress status` command - https://cloud.ibm.com/docs/containers?topic=containers-cli-plugin-kubernetes-service-cli#cs_ingress_status

Example output
```
ibmcloud ks ingress status -c my-cluster
OK
                     
Ingress Status:   healthy   
Message:          All Ingress components are healthy   

Component             Status    Type   
certificate manager   healthy   secret   
router-default        healthy   router
```
