### ISSUE TITLE
COS upgrade instruction

### ISSUE THREAD

**Issue by EddieKSpin** [ibm-cloud-docs/containers#2576]
https://cloud.ibm.com/docs/containers?topic=containers-object_storage#update_cos_plugin

the documentation suggest that we delete the existing installation and reinstall.

However , in the documentation on removing installation states 

`Removing the ibmc Helm plug-in or the ibm-object-storage-plugin does not remove existing PVCs, PVs, data. When you remove the ibm-object-storage-plugin, all the related pods and daemon sets are removed from your cluster. You cannot provision new IBM Cloud Object Storage for your cluster or use existing PVCs and PVs after you remove the plug-in, unless you configure your app to use the IBM Cloud Object Storage API directly.`

Does this mean that there will be service disruption? Would a simple helm upgrade not suffice?

**Comment by derekpoindexter** [comment]
Hi, yes - helm upgrade also works. Thank you for the feedback. I've updated this page.
