### ISSUE TITLE
Ghost and missing commands.

### ISSUE THREAD

**Issue by kylek3h** [ibm-cloud-docs/containers#2580]
https://cloud.ibm.com/docs/containers?topic=containers-istio-mesh#istio_expose_bookinfo_tls

I’m trying to follow the setup steps and there are blatant errors in it.  
Step 1 looks blank but you can barely see it’s a super light grey text on a white background.
Step 3 is not even a complete command line.  It’s completely an unfinished thought.

There are 2 or 3 other places throughout the page that has ghost commands.  You can't see them, but if you use the `copy` link you get them in your cut-n-paste buffer.

**Comment by derekpoindexter** [comment]
@kylek3h Thanks for the feedback. We're working on a fix.

**Comment by derekpoindexter** [comment]
@kylek3h - We've pushed a fix for this issue. Thanks again
