### ISSUE TITLE
It should be ... kubectl get pod -n kube-system | grep block

### ISSUE THREAD

**Issue by tnakajo** [ibm-cloud-docs/containers#2582]
https://cloud.ibm.com/docs/containers?topic=containers-block_storage#install_block

Verify that the installation was successful.

kubectl get pod -n <namespace> | grep block

It should be...

kubectl get pod -n kube-system | grep block

**Comment by derekpoindexter** [comment]
Hi, thank you for the feedback. I've update the example command.
