### ISSUE TITLE
Broken links in topic containers-registry

### ISSUE THREAD

**Issue by kgibm** [ibm-cloud-docs/containers#2584]
https://cloud.ibm.com/docs/containers?topic=containers-registry#other

Screenshot showing the broken links:

![img](https://user-images.githubusercontent.com/6618433/133335870-077c4f3f-260e-4539-a29f-404e45f1d9b7.png)

**Comment by derekpoindexter** [comment]
Hi, thank you for the feedback. I've updated the formatting on this page.
