### ISSUE TITLE
Autoscaler Secret Troubleshooting - Outdated Docs

### ISSUE THREAD

**Issue by ssalerno-ibmcloud** [ibm-cloud-docs/containers#2585]
[containers-ca_ts_secret](https://cloud.ibm.com/docs/containers?topic=containers-ca_ts_secret)

This documentation is outdated - this container is no longer built as part of the add-on, so the documentation should be updated or removed.

**Comment by derekpoindexter** [comment]
Hi, thank you for the feedback. I've removed this page.
