### ISSUE TITLE
Problems with Code Blocks in Block Storage/File Storage documentation

### ISSUE THREAD

**Issue by MatthewLemmond** [ibm-cloud-docs/containers#2586]
Looking through the documentation, it appears there are some issues with a few of the YAML code blocks used to show examples for PVC/PV creation, one specific example of this is found in step 5 at this link: https://cloud.ibm.com/docs/containers?topic=containers-block_storage#existing-block-2

I've noticed this in both the block and file storage documentations, can add further examples if needed.

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've updated the page.
