### ISSUE TITLE
Wrong formatting on page

### ISSUE THREAD

**Issue by mihivagyok** [ibm-cloud-docs/containers#2587]
The following page has wrong formatting:
https://cloud.ibm.com/docs/containers?topic=containers-cs_ssh_worker#kubectl-exec

![image](https://user-images.githubusercontent.com/18672841/133730888-de4b602e-0376-4ff3-8d98-6c926a132cdb.png)

Also, here: https://cloud.ibm.com/docs/containers?topic=containers-cs_ssh_worker#pod-ssh

Step 3, the manifest file has an issue, the args shall be this:
```
    args: ["-c", "echo $(SSH_PUBLIC_KEY) | tee -a /root/.ssh/authorized_keys && sed -i 's/PermitRootLogin.*/PermitRootLogin yes/g' /host/etc/ssh/sshd_config && killall -1 sshd && while true; do sleep 86400; done"]
```
(one less backslash)

Thank you!

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've updated the docs
