### ISSUE TITLE
Incorrect kubectl command within alb create classic

### ISSUE THREAD

**Issue by martyg1987** [ibm-cloud-docs/containers#2593]
Hi There, 

We have noticed an incorrect command in the create alb classic section here - https://cloud.ibm.com/docs/containers?topic=containers-kubernetes-service-cli#cs_alb_create

In this section the kubectl command is incorrect. 

--ip IP
Optional: An IP address to assign to the ALB. This IP must be on the vlan that you specified and must be in the same zone as the ALB that you want to create. This IP address must not be in use by another load balancer or ALB in the cluster. To see the IP addresses that are currently in use, run **kubectl get svcs --all-namespaces**.

This would be **kubectl get svc --all-namespaces**

Regards
Mg

**Comment by derekpoindexter** [comment]
Hi, thank you for the feedback. I've updated the command.
