### ISSUE TITLE
Missing steps for Creating an IAM trusted profile for your cluster in the UI

### ISSUE THREAD

**Issue by Aerex** [ibm-cloud-docs/containers#2597]
## Context
When trying to create authenticate a pod to use IBM Cloud services I realized that in the UI does not give you the ability to create a link to a computed resource for a trusted profile. I didn't realize that I needed this link until I tried to generate a IAM using the CR Token. I got the following error
```
{
    "errorCode": "BXNIM0398E",
    "errorMessage": "Selected trusted profile not eligible for CR token",
    "errorDetails": "The given compute resource token is not permitted to assume the indicated trusted profile; profile ID 'Profile-XXX, profile name 'null', profile CRN 'null'",
    ...
}
```

I was able to fix using the CLI to create the link mentioned above. I think this step should be included or add new troubleshooting step on how to fix this error if the user receives it. 

Below are the steps I took to make the link via the CLI. *Note: In my case, I was using a IBMCloud Kubernetes Cluster*

1. Retrieve the CRN of the cluster instance / VSI instance. The CRN will only show via the JSON output. You can use a program like `jq` to parse and select the `crn` value.
```
ibmcloud ks cluster get --cluster <cluster-name or ID> --output JSON | jq -r '.crn'
```

2. Retrieve the service account name
```
kubectl get serviceaccount -o jsonpath='{.items[0].metadata.name}'
```
3. Retrieve the namespace for the service account name in step 2 
```
kubectl get serviceaccount -o jsonpath='{.items[0].metadata.namespace}'
```

4. Create the link for the trusted profile 
```
ibmcloud iam tp-link-create <profile-name|profile-ID>  --name <any-name-for-the-link> --cr-type IKS_SA --link-crn <crn-from-step-1> --link-name <service-account-name-from-step-2>  --link-namespace <service-account-namespace-from-step-3>
```

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback.

For this issue: `UI does not give you the ability to create a link to a computed resource for a trusted profile`

The link is created automatically when you create the profile in the UI. You can verify this by creating the profile in the UI and assigning access.

Then in the CLI run `ibmcloud iam tps` to list your trusted profiles. Then run `ibmcloud iam tp-links <profile-id>` and pass in the trusted profile you created in the UI to get the link ID.

However, I noticed when testing the example Job that we had an extra `=` in the Job spec, which caused a similar error to the one you mentioned `"errorMessage": "Selected trusted profile not eligible for CR token",` - with the error being similar to this: 

```
"errorDetails":"The given compute resource token is not permitted to assume the indicated trusted profile; profile ID '=Profile
```

note the extra `=` - which was present in the example Job yaml. I've updated the yaml and clarified a few things in the docs. The changes will go live with our next promotion.
