### ISSUE TITLE
"Monitoring cluster health" table "App level metrics" has text in wrong column

### ISSUE THREAD

**Issue by frostmar** [ibm-cloud-docs/containers#2600]
In table _"App level metrics"_ the row including _"Number of pods per node reaching threshold of 110."_ has some text in the wrong column

![image](https://user-images.githubusercontent.com/3381992/140782016-f70de5cd-a771-489a-88c8-cdbe1163f951.png)

**Comment by daniel-p-miller** [comment]
Mark, I've updated the doc. Thank you!
