### ISSUE TITLE
Step 9 needs more explanation

### ISSUE THREAD

**Issue by knobutan** [ibm-cloud-docs/containers#2602]
Step in Forwarding Kubernetes API audit logs to Log Analysis should have more explanation. Especially regarding the fact that https://127.0.0.1:2040/api/v1/namespaces/default/services/ibmcloud-kube-audit-service/proxy/post uses a loopback address, so no need to use external IP.

Also, step 10 describes the output as:
```
OK
Server: http://172.21.xxx.xxx
Policy: default
```

However as the remote-server is not the clusterIP of kube-audit service, the real output from my cluster is:
```
OK
Server: https://127.0.0.1:2040/api/v1/namespaces/default/services/ibmcloud-kube-audit-service/proxy/post 
```

Please review.

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've updated the docs to remove the reference to cluster IP and updated the example output. The change will go live with our next prod promotion.
