### ISSUE TITLE
Tutorial docker command issues

### ISSUE THREAD

**Issue by petercort** [ibm-cloud-docs/containers#2603]
On the tutorial lesson 2:  https://cloud.ibm.com/docs/containers?topic=containers-cs_cluster_tutorial#cs_cluster_tutorial_lesson2

1. Docker commands in Step 3.3 and 4.2 are missing the 'build' argument in the code snippet. 

2. There should be a push command after each docker build step (3.3, 4.2, 5.2), currently that is being omitted. 

`docker push <region>.icr.io/<namespace>/<repo>:<image#>`

3. The docker build command in 5.2 is perhaps referencing an old bit of ibmcloud cli functionality(?) but <ibmcloud cr docker> isn't a registered command.

**Comment by yingyeliu** [comment]
Thanks for your feedback. We have updated the documentation accordingly.
