### ISSUE TITLE
Test commands do not provide output

### ISSUE THREAD

**Issue by jamesbeltonIBM** [ibm-cloud-docs/containers#2604]
I'm reviewing the information on page https://cloud.ibm.com/docs/containers?topic=containers-vpc-firewall
Note: I am not behind a firewall of any kind, so I know ports are not blocked. I am logged into IBM Cloud via the CLI (`ibmcloud login -sso`)
Running the command: `curl https://containers.cloud.ibm.com/v1/` as per docs results in `{"error":"Not found"}` message. 
Running the command: `curl https://us.icr.io/api/v1/messages` outputs nothing (not even an error).

I was reviewing this since it's being placed into ICCT education but neither commands seem to be a valid connection test.

**Comment by yingyeliu** [comment]
The message with the big boat was removed. We have updated the doc instructions to use the zone api instead. Related issue is at: https://github.ibm.com/alchemy-containers/documentation/issues/8020 Thanks.
