### ISSUE TITLE
Error in Step5 

### ISSUE THREAD

**Issue by bkoohi** [ibm-cloud-docs/containers#2605]
The following doc: https://cloud.ibm.com/docs/containers?topic=containers-policy_tutorial

In step #5 it says:
"Verify that you can publicly access the app that is exposed by the NLB from your computer.

Get the public EXTERNAL-IP address of the NLB."

In the actual output of  "kubectl get svc -o wide" command under EXTERNAL-IP, there is no public IP displayed and it actually shows DNS name. There is a need to do nslookup to find the IP mapping to DNS name.

**Comment by daniel-p-miller** [comment]
Hello bkoohi, the documentation has been updated. Thank you!
