### ISSUE TITLE
request to update portworx support doc

### ISSUE THREAD

**Issue by powerjohn** [ibm-cloud-docs/containers#2606]
[this](https://cloud.ibm.com/docs/containers?topic=containers-service-partners#portworx-billing-support) doc is pointing to an archived channel portworx-on-iks can you update to the relevant support avenue

**Comment by derekpoindexter** [comment]
Hey thanks for the feedback, I've got a pr to update this page that will go live with our next prod push. For now, the correct support process is here - https://cloud.ibm.com/docs/containers?topic=containers-portworx#portworx_help_sup
