### ISSUE TITLE
the numbering of steps is confusing in the section Debugging by creating a pod with root SSH access

### ISSUE THREAD

**Issue by tnakajo** [ibm-cloud-docs/containers#2613]
The doc section Debugging by creating a pod with root SSH access covers Private network & Public network classic clusters that are connected to a public VLAN only & Cleaning up after debugging , the numbering of steps is confusing for readers. (Need to improve the doc.)

https://cloud.ibm.com/docs/containers?topic=containers-cs_ssh_worker#public-network-only-classic-debug

In the section Debugging by creating a pod with root SSH access, https://cloud.ibm.com/docs/containers?topic=containers-cs_ssh_worker#pod-ssh,

Current: 

Important: ..... be sure to follow step 7 in .....

(1)
(2)
(3)
(4)
(5)
Private Network
(1)
(2)
(3)
(4)
Public network classic clusters that are connected to a public VLAN only
(1)
(2)
(3)
(4)
Cleaning up after debugging
(1)
(2)
(3)

Suggesting:

Important: ..... be sure to follow step 6 in .....

(1)
(2)
(3)
(4)
(5) Use the private or public network to access the worker node by using your SSH key.

  (5-a). Private Network
    (a1)
    (a2)
    (a3)
    (a4)

  (5-b). Public network classic clusters that are connected to a public VLAN
    (b1)
    (b2)
    (b3)
    (b4)

(6) Cleaning up after debugging
   (a)
   (b)
   (c)

**Comment by yingyeliu** [comment]
Linked PR: https://github.ibm.com/alchemy-containers/documentation/pull/8513
