### ISSUE TITLE
Unsupported IKS version 1.19 can still be updated to a newer version ? 

### ISSUE THREAD

**Issue by Cathal2020** [ibm-cloud-docs/containers#2614]
Hi Team , just noticed that 1.19 which is unsupported , the docs say that it can still updated to later versions where as older versions (1.18 and lower ) a new cluster needs to be provisioned and the workload migrated over . 

So is it correct that 1.19 can still updated to 1.20 ? 
https://cloud.ibm.com/docs/containers?topic=containers-cs_versions#cs_v119

Thanks.

**Comment by derekpoindexter** [comment]
Hi, yes 1.19 can still updated to 1.20.

You can follow the steps here that discuss pre/post update considerations: https://cloud.ibm.com/docs/containers?topic=containers-cs_versions_120#prep-up-120. 

Then, during master update, you can pass the `--version` flag to specify at least the `major.minor` version you want to get to - https://cloud.ibm.com/docs/containers?topic=containers-kubernetes-service-cli#cs_cluster_update 
You can also specify the `major.minor.patch` version, but only `major.minor` are required.

To list the available versions, you can run the versions command here - https://cloud.ibm.com/docs/containers?topic=containers-kubernetes-service-cli#cs_versions_command

And here is the 1.20 change log - https://cloud.ibm.com/docs/containers?topic=containers-changelog_120
