### ISSUE TITLE
correction re: ic ks api-key reset

### ISSUE THREAD

**Issue by powerjohn** [ibm-cloud-docs/containers#2615]
Hi, in the section `ic ks api-key reset` it states in the [IMPORTANT notice](https://cloud.ibm.com/docs/containers?topic=containers-kubernetes-service-cli#cs_api_key_reset)
`Target the resource group and region that you want to set the API key for. When the API key is reset, the previous API key that was used, if any, for the region and resource group is deleted.`
This is not completely true, the apikey remains in the list at https://cloud.ibm.com/iam/apikeys
Perhaps changing this to `the apikey becomes obsolete and can safely be manually deleted` would reflect the scenario better?

**Comment by daniel-p-miller** [comment]
John, thanks for raising this issue. The documentation will be updated!
