### ISSUE TITLE
Incorrect link to IKS documentation from cloud.ibm.com/docs

### ISSUE THREAD

**Issue by Matthew-Wroblewski** [ibm-cloud-docs/containers#2616]
Incorrect link to IKS documentation from cloud.ibm.com/docs

Steps to Reproduce:
   1. go to ibm.cloud/docs
   2. Click on the "products" tab on the top bar and then "containers" in the drop-down menu on the left.
   3. Click on  "IBM Cloud Kubernetes Service" and you will see it links to the Container Registry docs instead of IKS.

(screenshot included below)

<img width="1715" alt="Screen Shot 2022-04-01 at 9 34 18 AM" src="https://user-images.githubusercontent.com/27292002/161275401-51614025-6cdf-4b5d-9220-d2283b61da52.png">

**Comment by derekpoindexter** [comment]
Hey, thanks for the feedback. We've updated the link.
