### ISSUE TITLE
Wrong command at Verify your installation section.

### ISSUE THREAD

**Issue by guilhermecreste** [ibm-cloud-docs/containers#2617]
At Verify your installation section, there is one command to set one storageclass as the default storageclass. There is an extra space in the command.

It is now as:
`kubectl patch storage class <storageclass> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'. Replace <storageclass>`

And it should be:
`kubectl patch storageclass <storageclass> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'. Replace <storageclass>`

**Comment by yingyeliu** [comment]
Fixed. Thanks.
