### ISSUE TITLE
Request for updating the docs for cs_ssh_worker

### ISSUE THREAD

**Issue by tnakajo** [ibm-cloud-docs/containers#2618]
We need to update the docs with the following:

Debugging by creating a pod with root SSH access
https://cloud.ibm.com/docs/containers?topic=containers-cs_ssh_worker#pod-ssh
https://cloud.ibm.com/docs/openshift?topic=openshift-cs_ssh_worker#pod-ssh

1. Choose an existing or create a new public SSH key.

$ ssh-keygen -t rsa -b 4096
$ ls ~/.ssh
id_rsa		id_rsa.pub
$ cat ~/.ssh/id_rsa.pub

Public network classic clusters
https://cloud.ibm.com/docs/containers?topic=containers-cs_ssh_worker#public-network-only-classic-debug
https://cloud.ibm.com/docs/openshift?topic=openshift-cs_ssh_worker#public-network-only-classic-debug

4. SSH into the worker node via its public IP address. 

ssh root@<WORKER_PUBLIC_IP>

**Comment by yingyeliu** [comment]
Fixed. Thanks.
