### ISSUE TITLE
Wrong command in banner

### ISSUE THREAD

**Issue by dhyey-ibm** [ibm-cloud-docs/containers#2619]
![image](https://user-images.githubusercontent.com/24547445/162801355-34eed10b-c324-42d9-8f1c-cd9c615c128d.png)

Current command: `ibmcloud nlb-dns secret rm`
Should be: `ibmcloud ks nlb-dns secret rm`

**Comment by daniel-p-miller** [comment]
Dhyey, thanks for bringing this to our attention. The command will be updated shortly!
