### ISSUE TITLE
URL to site is pointing to the wrong site

### ISSUE THREAD

**Issue by morallito** [ibm-cloud-docs/containers#2620]
I am reading the docs about creating a persistent storage using the [file storage](https://cloud.ibm.com/docs/containers?topic=containers-kube_concepts), and in the image below you can see that there is a link `ibm.io/ibmc-file`. This link points me to a portfolio of a random guy, not to an IBM doc. 

![Captura de Tela 2022-04-18 às 08 06 48](https://user-images.githubusercontent.com/19959302/163799886-bc74a36d-c36f-4d07-b39b-ae58a6923079.png)
![Captura de Tela 2022-04-18 às 08 08 49](https://user-images.githubusercontent.com/19959302/163800048-3f687aee-a3ed-4bf6-a41a-3c46b782ab34.png)

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. The value in parenthesis (ibm.io/ibmc-file) is referring to the provisioner/driver, rather than a URL. I've removed this from the image. This change will go live with our next promotion.
