### ISSUE TITLE
Correction: Registering a Secrets Manager instance to a cluster

### ISSUE THREAD

**Issue by tnakajo** [ibm-cloud-docs/containers#2621]
Section: Registering a Secrets Manager instance to a cluster

IKS: https://cloud.ibm.com/docs/containers?topic=containers-ingress-types#register-secrets-mgr

WRONG:
ibmcloud ks register --cluster <cluster_name_or_id> --crn <instance_crn>

CORRECT:
ibmcloud ks ingress instance register <cluster_name_or_id> --crn <instance_crn>

ROKS: https://cloud.ibm.com/docs/openshift?topic=openshift-ingress-roks4#register-secrets-mgr

WRONG:
ibmcloud oc register --cluster <cluster_name_or_id> --crn <instance_crn>

CORRECT:
ibmcloud oc ingress instance register <cluster_name_or_id> --crn <instance_crn>

**Comment by derekpoindexter** [comment]
Hey, thanks for the feedback. We've updated the example commands.
