### ISSUE TITLE
Incomplete Ingress instructions

### ISSUE THREAD

**Issue by frykshon** [ibm-cloud-docs/containers#2622]
This part of the doc is confusing:
https://cloud.ibm.com/docs/containers?topic=containers-ingress-types#alb-com-create-ibm-domain

When trying to setup an IBM-provided domain the instructions seem to be missing the part where you deploy the ingress. Section 4 of the custom domain has this example ingress that would be good to use but the ibm domain part could use some clarification:

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: community-ingress-resource
  annotations:
    kubernetes.io/ingress.class: "public-iks-k8s-nginx"
spec:
  tls:
  - hosts: 
    - HOSTNAME
    secretName: SECRET_NAME
  rules:
  - host: HOSTNAME
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: nginx-auth
            port:
              number: 80

**Comment by frykshon** [comment]
Comparing to the openshift docs it looks like maybe that Ingress section wasn't sectioned out into its own part, here's the example from the ibmcloud openshift docs:
https://cloud.ibm.com/docs/openshift?topic=openshift-ingress-roks4#ingress-roks4-public-3

**Comment by marissa-treible** [comment]
Hi @frykshon. Thanks for bringing this to our attention. I rearranged the sections to clarify when the deploy ingress resource steps should be completed. The changes should be available this afternoon.
