### ISSUE TITLE
Incorrect Terminology - Istio Setup Page

### ISSUE THREAD

**Issue by ssalerno-ibmcloud** [ibm-cloud-docs/containers#2623]
[Containers-Istio](https://cloud.ibm.com/docs/containers?topic=containers-istio#update_client_sidecar)

Erroneous statement:
```
Classic multizone clusters: Ensure that you enable a [Virtual Router Function (VRF)](https://cloud.ibm.com/docs/account?topic=account-vrf-service-endpoint#vrf) for your IBM Cloud infrastructure account.
```

Corrected Statement:
```
Classic multizone clusters: Ensure that you enable [Virtual Routing and Forwarding (VRF)](https://cloud.ibm.com/docs/account?topic=account-vrf-service-endpoint#vrf) for your IBM Cloud infrastructure account.
```

The acronym VRF in this context is defined as _Virtual Routing and Forwarding_ and **not** "_Virtual Router Function_". See also [VRF Setup Instructions](https://cloud.ibm.com/docs/account?topic=account-vrf-service-endpoint&interface=ui#vrf) for a page where VRF is correctly defined.

**Comment by yingyeliu** [comment]
Fixed. Thanks.
