### ISSUE TITLE
List formatting issue in containers-debug_metrics_server

### ISSUE THREAD

**Issue by jmcmeek** [ibm-cloud-docs/containers#2624]
https://cloud.ibm.com/docs/containers?topic=containers-debug_metrics_server

The topic end with these two indented bulleted items:

  - If you get an error message that contains text such as `<workerIP>:10250: getsockopt: connection timed out`, see [kubectl commands time out](https://cloud.ibm.com/docs/containers?topic=containers-ts_clis#exec_logs_fail).

  - If the previous steps do not show a problem, adjust the resources for the metrics-server. See [Adjusting cluster metrics provider resources](https://cloud.ibm.com/docs/containers?topic=containers-kernel#metrics).

The last of those should be outdented to to continue the numbered list.  e.g.

1. Verify that metrics-server pods exist.

    blah blah

2. Verify that the apiserver can connect to the metrics-server.

    blah blah

    - If you get an error message that contains text such as `<workerIP>:10250: getsockopt: connection timed out`, see [kubectl commands time out](https://cloud.ibm.com/docs/containers?topic=containers-ts_clis#exec_logs_fail).

3.  If the previous steps do not show a problem, adjust the resources for the `metrics-server`. See [Adjusting cluster metrics provider resources](https://cloud.ibm.com/docs/containers?topic=containers-kernel#metrics).

**Comment by yingyeliu** [comment]
Fixed. Thanks.

**Comment by jmcmeek** [comment]
Thanks! That looks better.  It was kind of a nit, but it made the tuning information hard to find.
