### ISSUE TITLE
resize2fs isn't installed by default in Ubuntu, apparently including containers

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/containers#2629]
ACS-VPC support here - customer opened a case with us after successfully expanding a VPC block storage volume, but were unable to increase the filesystem to make use of it:

/sbin$ resize2fs /dev/vde
bash: resize2fs: command not found

Ubuntu manpage shows this command is provided by the e2fsprogs package.  I suspect this package is not installed in IKS pods by default, so the documentation should probably need to be updated to include a step to install the package that provides it:

https://manpages.ubuntu.com/manpages/xenial/man8/resize2fs.8.html

**Comment by derekpoindexter** [comment]
Hey, thanks for the feedback. I've opened a defect with storage team.

**Comment by derekpoindexter** [comment]
Hi, the steps for using resize2fs were for an earlier plugin version, can you try updating to plugin version 4.2 and following the steps here - https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-block#vpc-block-volume-expand - I will reach out internally for the customer ticket details.
