### ISSUE TITLE
Need more specific for the value <name> & <namespace> in the command

### ISSUE THREAD

**Issue by tnakajo** [ibm-cloud-docs/containers#2631]
We need more specific for the value <name> & <namespace> in the command. ... to avoid confusion to users.

https://cloud.ibm.com/docs/containers?topic=containers-block_storage#update_block

*CURRENT*
Step 4:
Upgrade the IBM Cloud Block Storage plug-in to the latest version.

helm upgrade *name* iks-charts/ibmcloud-block-storage-plugin -n *kube-system*

*EXPECTED*
Upgrade the IBM Cloud Block Storage plug-in to the latest version.
Note: Replace the values *release name* and *namespace* with the release name and namespace of the block 
storage Helm chart that you find in the previous step.

helm upgrade *release name* iks-charts/ibmcloud-block-storage-plugin -n *namespace*

**Comment by derekpoindexter** [comment]
Hey, thanks for the feedback. I've updated this step. The change will be live with our next promotion.
