### ISSUE TITLE
Please add more info.

### ISSUE THREAD

**Issue by vmtkac-coe** [ibm-cloud-docs/containers#2632]
I was directed to this page from IBM Cloud in response to my cluster having a worker in critical state.  

```
You have nodes in critical state, try the following to resolve
1. Update your cluster and worker nodes to the latest versions.
2. Update your command line tools.
3. Run the tests in the Diagnostics and Debug Tool add-on.
```

The page doesn't help me resolve the issue.  Please add a suggestion to:

reboot the work:
ibmcloud ks worker reboot --cluster <cluster_name_or_id> --worker <worker_node_id>

update kubernetes on the worker:
ibmcloud ks worker update --cluster <cluster_name_or_id> --worker <worker_node_id>

reload the the worker with a new image:
ibmcloud ks worker reload --cluster <cluster_name_or_id> --worker <worker_node_id>

**Comment by marissa-treible** [comment]
Hi @vmtkac-coe. Could you provide a link to the doc page you are referring to?

We also have additional troubleshooting topics in our documentation that may help you resolve your issue, [including this one on worker node states](https://cloud.ibm.com/docs/containers?topic=containers-worker-node-state-reference#worker-node-critical). 

Thank you.

**Comment by marissa-treible** [comment]
@vmtack-coe I believe this page is in our UI rather than our documentation. I'll open an issue with our UI team to have the instructions updated. Thank you.

**Comment by vmtkac-coe** [comment]
Hi, I believe it was this page:

https://cloud.ibm.com/kubernetes/clusters/c9bibsod0q9i17gm8ij0/nodes?region=us-south&resourceGroup=5c8a73ce0d3448b3b8964fe1f9218b3a

Here is what the page looked like.  I clicked the "view doc" link expecting to get more info on how to do those things.  

<img width="1181" alt="Screen Shot 2022-05-31 at 9 26 26 AM" src="https://user-images.githubusercontent.com/97244224/171656272-b00980ec-96f0-4fd4-a747-9af781e8e3d3.png">

**Comment by marissa-treible** [comment]
@vmtkac-coe Thanks for the additional info. I added the steps to the doc page linked in that warning (https://cloud.ibm.com/docs/containers?topic=containers-debug_worker_nodes).
