### ISSUE TITLE
Inaccurate Change Log

### ISSUE THREAD

**Issue by frykshon** [ibm-cloud-docs/containers#2633]
It seems the [K8s ingress change log](https://cloud.ibm.com/docs/containers?topic=containers-cluster-add-ons-changelog) is not up to date. Here are the current versions pulled via the cli:

```
$ ibmcloud ks ingress alb versions
OK
Kubernetes Ingress versions   
1.2.0_2306_iks (default)   
1.1.2_2305_iks   
0.49.3_2304_iks   
$
```

But as you can see in change log [1.2.0](https://cloud.ibm.com/docs/containers?topic=containers-cluster-add-ons-changelog#1.2.0_2251_iks) only goes up to 1.2.0_2251_iks and does not cover 1.2.0_2306_iks. The [1.1.2](https://cloud.ibm.com/docs/containers?topic=containers-cluster-add-ons-changelog#1.1.2_2252_iks) only covers 1.1.2_2252_iks and not 1.1.2_2305_iks.

Can this change log be updated to include the current versions?

**Comment by yingyeliu** [comment]
Fixed. Thanks.
