### ISSUE TITLE
VRF full form

### ISSUE THREAD

**Issue by abhishektuf** [ibm-cloud-docs/containers#2634]
Under the heading "What are Virtual Router Functions (VRF) and VLAN spanning?" the correct name is "Virtual Routing and Forwarding" for VRF. We need to change all the references.

Incorrect Term :  Virtual Router Functions
Short form/Abbreviation : VRF
Correct Term : Virtual Routing and Forwarding

Page URL : https://cloud.ibm.com/docs/containers?topic=containers-subnets#basics_segmentation

**Comment by daniel-p-miller** [comment]
Thanks for the feedback, we've made that change!
