### ISSUE TITLE
Incorrect credential set usage

### ISSUE THREAD

**Issue by enakatani** [ibm-cloud-docs/containers#2635]
Command at 2 - b in "Accessing a different classic infrastructure account" section at the following link is incorrect:
https://cloud.ibm.com/docs/containers?topic=containers-access-creds#credentials

2 -b

Current:
ibmcloud ks credential set --infrastructure-username <infrastructure_API_username> --infrastructure-api-key <infrastructure_API_authentication_key> --region <region>

Correct one:
ibmcloud ks credential set **_classic_** --infrastructure-username <infrastructure_API_username> --infrastructure-api-key <infrastructure_API_authentication_key> --region <region>

**Comment by daniel-p-miller** [comment]
Thanks for the feedback, we've made that change!
