### ISSUE TITLE
Doc Update - PR Submitted

### ISSUE THREAD

**Issue by ssalerno-ibmcloud** [ibm-cloud-docs/containers#2641]
Created PR to notify of doc update opportunity - see #2640 . 

Ignore the whitespace edits; as usual, Atom likes to remove them. There is only 1 real change in the PR - line 1543 of _storage-portworx.md_.

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've made the fix in our internal source. It will go out with the next promotion.
