### ISSUE TITLE
how to upgrade portworx version if the client is in air-gapped environment on IBM Cloud

### ISSUE THREAD

**Issue by ketanvora15** [ibm-cloud-docs/containers#2642]
**Service(s) involved**
1] Portworx; IKS; Openshift

**What information is missing in the Doc:**
how to upgrade portworx version if the client is in air-gapped environment on IBM Cloud

**A brief description of the missing Process in the docs:**
1] Client must first open a support case with portworx directly,
2] Get the Portworx support case number
3] Open a support case with IBM Cloud.
4] Provide the case number in the IBM Cloud Case, so our IKS can communicate directly with portworx.

**Link for the revenant docs where the above knowledge gap needs to be filled:**
https://cloud.ibm.com/docs/containers?topic=containers-portworx

**Note: I think, the ideal place would be FAQ or Troubleshooting sections.**

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I added this to the updating section. It will go live with our next promotion.
