### ISSUE TITLE
caclicoctl releases have moved to https://github.com/projectcalico/calico/releases

### ISSUE THREAD

**Issue by melickm** [ibm-cloud-docs/containers#2644]
In: https://cloud.ibm.com/docs/containers?topic=containers-network_policies#cli_install the link is step 3 points to an older repository where the caclicoctl is not longer maintained and newer versions aren't available.

Per the announcement here: https://github.com/projectcalico/calicoctl#source-code-moved the caclicoctl is now maintained at: https://github.com/projectcalico/calico and the releases are at https://github.com/projectcalico/calico/releases

**Comment by daniel-p-miller** [comment]
Thanks for bringing this to our attention, the link will be updated with our next push!
