### ISSUE TITLE
confusing default values for Cluster autoscaler add-on parameter reference 

### ISSUE THREAD

**Issue by Brenne** [ibm-cloud-docs/containers#2645]
Some default values for [Cluster autoscaler add-on parameter reference](https://cloud.ibm.com/docs/containers?topic=containers-cluster-scaling-install-addon#ca_addon_ref) are confusing:

> livenessProbePeriodSeconds
>     Specify the interval in seconds that the kubelet performs a liveness probe. The default value is 10m.

Why 10m? while the default for `livenessProbeTimeoutSeconds` is just `10` without an `m`:

> livenessProbeTimeoutSeconds
>     Specify the time in seconds after which the liveness probe times out. The default value is 10.

-----------------
> maxRetryGap
>     Set the maximum time in seconds [...] The default value is 60m.

The time is set in seconds but the default value is `60m` ? This sounds confusing.

**Comment by daniel-p-miller** [comment]
Thanks for bringing this to our attention, the page has been updated!
