### ISSUE TITLE
ALB version in ibmcloud ks ingress alb command examples invalid

### ISSUE THREAD

**Issue by enakatani** [ibm-cloud-docs/containers#2647]
"ibmcloud ks ingress alb" command examples at the following page still are still using 1.2.1_2337_iks which is not valid any more:
https://cloud.ibm.com/docs/containers?topic=containers-ingress-types

Current valid version is 1.2.1_2506_iks. Please update the version or maybe add reference to:
https://cloud.ibm.com/docs/containers?topic=containers-ingress-types#alb-version-choose

In this way, the document will not need to be updated every time new version is available.

**Comment by marissa-treible** [comment]
@enakatani Thanks for opening the issue. The version is updated and the changes will be released in our next publish.
