### ISSUE TITLE
Add a section to deploy sysdig agent on Edge Worker Node.

### ISSUE THREAD

**Issue by lionelmace** [ibm-cloud-docs/containers#2648]
Sysdig agent will not get deployed on Edge worker nodes

Proposition:
On this page https://cloud.ibm.com/docs/containers?topic=containers-edge, we should add a section similar to this:

Section Title: Deploy Sysdig agent on Edge worker node
Section Content:
to make sure Sysdig agent gets deployed on tainted edge worker node:
`kubectl patch ds sysdig-agent -n ibm-observe --type merge --type='json' -p='[{"op": "add", "path": "/spec/template/spec/tolerations/-", "value": {"operator": Exists, "effect": NoExecute}}]'`

**Comment by derekpoindexter** [comment]
Hey thanks for the feedback. I've added a section for sysdig on edge that will go live later today.
