### ISSUE TITLE
Need to make it easier for customer to find SL API Username

### ISSUE THREAD

**Issue by monica-suarez** [ibm-cloud-docs/containers#2649]
https://cloud.ibm.com/docs/containers?topic=containers-access-creds#credentials

In this specific section, we should instruct the customer how to find their infrastructure username, by putting the `ibmcloud sl user list` in this section of the document. It makes no sense that we would ask them to execute a command, but not how to find one of the parameters of the command.

**Comment by daniel-p-miller** [comment]
Thanks for bringing this to our attention, it will be updated shortly.
