### ISSUE TITLE
Spelling Mistake 

### ISSUE THREAD

**Issue by mkulamarva** [ibm-cloud-docs/containers#2653]
Hi Team

There is a spelling mistake in the below links for ibmcloud ks flavors (macine-types) , the h is missing in the machine-types, please correct it, thank you. 
https://cloud.ibm.com/docs/containers?topic=containers-kubernetes-service-cli#cs_worker_pool_create
https://cloud.ibm.com/docs/openshift?topic=openshift-kubernetes-service-cli#cs_worker_pool_create

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. The fix will go live later today.
