### ISSUE TITLE
List option for --operating-system flag.

### ISSUE THREAD

**Issue by abhishektuf** [ibm-cloud-docs/containers#2654]
https://cloud.ibm.com/docs/containers?topic=containers-kubernetes-service-cli#cs_worker_pool_create
https://cloud.ibm.com/docs/containers?topic=containers-kubernetes-service-cli#cli_worker_pool_create_vpc_gen2

In the above document link there is no mention of possible parameters for the `--operating-system` flag. Since from IKS version 1.25 Ubuntu 18 & Ubuntu 20 are available options.

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. The fix will go live later today. The possible parameters are listed in the supported operating systems page here - https://cloud.ibm.com/docs/containers?topic=containers-cs_versions
