### ISSUE TITLE
Migrating from IBM Cloud Certificate Manager to IBM Cloud Secrets Manager

### ISSUE THREAD

**Issue by suresh9494** [ibm-cloud-docs/containers#2655]
Hello Team,
This is regarding Step 2 on the below document. 
https://cloud.ibm.com/docs/containers?topic=containers-certs-mgr-migration#certs-mgr_setup_register
Looks like "set" command is not available with "ibmcloud ks ingress instance". Please check and update the document. Thanks.

Register the instance to your cluster. Specify the instance CRN found in the previous step.
If you want to register an instance to a cluster and also [set it as the default instance](https://github.com/ibm-cloud-docs/containers/blob/master/certs-mgr-migration.md#certs-mgr_setup_default), include the --is-default option. Otherwise, you can set a default instance with the ibmcloud ks ingress instance set command. {: tip}

❯ ibmcloud ks ingress instance
NAME:
        ibmcloud ks ingress instance - Manage registered instances of the IBM Cloud Secrets Manager.
USAGE:
        ibmcloud ks ingress instance command [arguments...] [command options]

COMMANDS:
    default      Update the default configuration of a registered IBM Cloud Secrets Manager instance.
    get          View the details of an IBM Cloud Secrets Manager instance.
    ls           List all instances of the IBM Cloud Secrets Manager.
    register     Register an IBM Cloud Secrets Manager instance to a cluster.
    unregister   Unregister an IBM Cloud Secrets Manager instance from a cluster.

**Comment by derekpoindexter** [comment]
Make sure you update your CLI

```sh
derek@Dereks-MBP ~ % ic ks ingress instance default
NAME:
        ibmcloud ks ingress instance default - Update the default configuration of a registered IBM Cloud Secrets Manager instance.
USAGE:
        ibmcloud ks ingress instance default command [arguments...] [command options]

COMMANDS:
    set     Set a registered IBM Cloud Secrets Manager instance as the default. If an existing default instance exists, it is unset.
    unset   Unset a registered IBM Cloud Secrets Manager instance from default.


Enter 'ibmcloud ks ingress instance default help [command]' for more information about a command.
derek@Dereks-MBP ~ % ic update
Checking for updates...
No update required. Your CLI is already up-to-date.
To view available plugin updates, run 'ibmcloud plugin list'.
derek@Dereks-MBP ~ % ic plugin update
Checking upgrades for all installed plug-ins from repository 'IBM Cloud'...
No updates are available.
derek@Dereks-MBP ~ % ic version
ibmcloud version 2.13.0+05fd406-2022-11-30T21:03:31+00:00
```
