### ISSUE TITLE
Document Issue - Looks like we need to edit the document for the command

### ISSUE THREAD

**Issue by kirankl9** [ibm-cloud-docs/containers#2656]
We were working on the case and the customer suggested as below:
----------------------------
Another remark; on your documentation the discovery command that is written is incorrect;
iscsiadm -m discovery -T sendtargets -p <ip-value-from-IBM-Cloud-console>
The "-T" should be "-t", otherwise the command fails. I suspect most Block storage users will encounter this issue.

Documentation link:
https://cloud.ibm.com/docs/BlockStorage?topic=BlockStorage-mountingRHEL8&interface=ui
----------------------------

Best Regards,       
Kiran K L
Storage Support Engineer
IBM Cloud Support

**Comment by derekpoindexter** [comment]
Hey thanks for the feedback. 

I opened an issue with the block storage docs team - https://github.ibm.com/cloud-docs/BlockStorage/issues/81 

The fix will go out soon.
