### ISSUE TITLE
Documentation needs an update

### ISSUE THREAD

**Issue by tschrenk-corp** [ibm-cloud-docs/containers#2662]
According to CS3306293 the documentation needs an update

zone="eu-de-1" works for region="eu-de"

---

Hello Shanmukha,

zone="eu-de-1" works for region="eu-de"

Documentation here https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/pi_catalog_images gives a valid example for London region (e.g. region="lon" & zone="lon04").

However, according to the documentation below, the correct zone values for Frankfurt region are -fra02, fra04, fra05 (just search for 'lon04', and see the revelant Frankfurt region).
https://cloud.ibm.com/docs/containers?topic=containers-regions-and-zones

Please can you check if the documnation can be updated with the correct information? Thanks.

Kind regards,
Qing Ye

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback.

This page - https://cloud.ibm.com/docs/containers?topic=containers-regions-and-zones covers the IBM Cloud zones for Classic and VPC infrastructure, specifically for creating Kubernetes clusters.

The page you mentioned here - https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/pi_catalog_images is referring to Power Systems regions. 

The regions and zone names differ between Power Systems, Classic, and VPC. You can see table here with the information - https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-creating-power-virtual-server#creating-service

The zone names for Power Systems in Frankfurt are `eu-de-1` and `eu-de-2`.

<img width="577" alt="Screenshot 2023-04-05 at 4 26 09 PM" src="https://user-images.githubusercontent.com/45565883/230202707-0994e5f9-8fab-4184-b0c3-097b4609e3d9.png">

**Comment by qye-r** [comment]
Hi derekpoindexter,

Thank you for providing the correct region and zone link for Power System.

We saw the link before but didn't find the correct region and zone example (region="lon" & zone="lon04) given by https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/pi_catalog_images, so moved to an incorrect link.

We think the documentation changes below will be helpful:
1. https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-creating-power-virtual-server#creating-service
- Update 'region', 'zone' and 'data center' with correct case-sensitive values.
- For example, 'eu-gb' is a wrong region for endpoints over a public network in London, also uppercase zone values won't work in terraform, etc.

2. https://registry.terraform.io/providers/IBM-Cloud/ibm/latest/docs/data-sources/pi_catalog_images
- Under Notes, add 'Please find supported zones' with the correct link in point #1.

Thanks.

Kind regards,
Qing Ye
