### ISSUE TITLE
pls fix a doc issue 

### ISSUE THREAD

**Issue by threen134** [ibm-cloud-docs/containers#2665]
step 1 output should not be public ip address 1.1.1.1 
it should be internal ip address 10.x.x.x , as the LB externalTrafficPolicy is Cluster in this step 1 , so the output should be 10.x.x.x which is internal client ip address 
![Xnip2023-06-05_16-33-16](https://github.com/ibm-cloud-docs/containers/assets/13844762/c7369c6d-8f0e-4f54-8153-2130d96a8222)
 

https://cloud.ibm.com/docs/containers?topic=containers-policy_tutorial#lesson1

**Comment by threen134** [comment]
this is a example before change to Local from cluster
![Xnip2023-06-05_16-36-50](https://github.com/ibm-cloud-docs/containers/assets/13844762/734a45ea-fa90-431d-a216-62e48016febf)

**Comment by yingyeliu** [comment]
Fixed. Thanks.
