### ISSUE TITLE
"for Classic" in File Storage for VPC pages

### ISSUE THREAD

**Issue by davesteinberg** [ibm-cloud-docs/containers#2666]
I see that there's a new (beta) File Storage for VPC option in Kubernetes service:
https://cloud.ibm.com/docs/containers?topic=containers-storage-file-vpc-install

However, other pages in this section of the docs repeatedly mention "for Classic":
https://cloud.ibm.com/docs/containers?topic=containers-storage-file-vpc-apps (14 occurrences)
https://cloud.ibm.com/docs/containers?topic=containers-storage-file-vpc-sc-ref (3 occurrences)

Is this a copy paste error, or are the different pages talking about two different capabilities: one "native" VPC File Storage, and the other that makes Classic File Storage available in a VPC cluster?

**Comment by daniel-p-miller** [comment]
Hey @davesteinberg Thanks for bringing this to our attention, this will be fixed shortly!
