### ISSUE TITLE
Istio data plane issues are customer's responsibility

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/containers#2668]
https://cloud.ibm.com/docs/containers?topic=containers-responsibilities_iks#applications-and-data

We get many cases opened against the Istio data plane.  We've been told that, while Istio control plane issues are IBM's responsibility, Istio data plane issues are the customer's responsibility.  Istio service mesh is complex enough that we frequently get pushback from customers when we tell them it's their responsibility.  The above link implies this, but does not explicitly state it.  Please let us know if that can be updated to explicitly document this.   Thanks!

**Comment by derekpoindexter** [comment]
Hey, thanks for the feedback. I've updated the page to call this out specifically. The update will be live soon.
