### ISSUE TITLE
"Updating Portworx in your cluster" has only VPC instructions

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/containers#2670]
https://cloud.ibm.com/docs/containers?topic=containers-storage_portworx_update

The above article contains instructions only for VPC clusters.  We will also need instructions for Classic Infrastructure clusters, if possible.  Thanks!

**Comment by derekpoindexter** [comment]
Hey, thanks for the feedback. I've updated the page to link back to this page - https://www.cloud.ibm.com/docs/containers?topic=containers-update&interface=ui#worker_node 

The change will be live soon.
