### ISSUE TITLE
Missing command after logging in to app pod, before running 'resize2fs'

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/containers#2674]
After using exec to log in to their app pod, before running 'resize2fs', customers need to first run 'chroot /host' or else they'll have problems with the resize2fs command or anything else to do with the mount table (mtab).

Also the exec command syntax in that article is in a deprecated style:

kubectl exec <pod-name> -it bash

The command should instead be:

kubectl exec <pod-name> -it -- bash

**Comment by derekpoindexter** [comment]
Hey, thanks for the feedback. I've updated the docs. The changes will be live later today.
