### ISSUE TITLE
addition to https://cloud.ibm.com/docs/containers?topic=containers-clusters

### ISSUE THREAD

**Issue by jmclemore84** [ibm-cloud-docs/containers#2676]
https://cloud.ibm.com/docs/containers?topic=containers-clusters

Hi team, I'm with the PaaS Core dev team and we would like a note added to this page that "Clusters are not able to be moved to different accounts"

We ask this because we have been getting chats and cases requesting this to be done. Once we let them know it's not possible they ask for a document referencing it. We do not have one and feel that a new one isn't needed; but a note could be added to an existing one.

**Comment by derekpoindexter** [comment]
Thanks for the feedback - i've added an entry to the faq here - https://cloud.ibm.com/docs/containers?topic=containers-faqs

it will be live later today
