### ISSUE TITLE
Missed Germany for classic flavours list in the docs

### ISSUE THREAD

**Issue by notras** [ibm-cloud-docs/containers#2678]
<img width="414" alt="Screenshot 2023-10-23 at 11 09 43" src="https://github.com/ibm-cloud-docs/containers/assets/43639563/b49e8a76-9d24-4034-8243-d682f33e5cfc">

Frankfurt definitely allow to use Classic flavors but it is not listed in the docs, please see attachment. 

link to the page with issue:
https://cloud.ibm.com/docs/containers?topic=containers-classic-flavors

**Comment by derekpoindexter** [comment]
Thanks for the feedback. I've merged a fix. It will be live soon.
