### ISSUE TITLE
The command example syntax for 'ibmcloud ks cluster addon get' is INCORRECT.

### ISSUE THREAD

**Issue by john-d-burke** [ibm-cloud-docs/containers#2679]
https://cloud.ibm.com/docs/containers?topic=containers-kubernetes-service-cli#cs_cluster_addon_get

The syntax example says:
ibmcloud ks get --addon ADDON --cluster CLUSTER [--output OUTPUT] [-q]

But the ACTUAL syntax is:
ibmcloud ks cluster addon get --addon ADDON --cluster CLUSTER [--output OUTPUT] [-q]

Tested to confirm:

>ibmcloud ks cluster addon get --addon debug-tool --cluster [REDACTED CLUSTER ID]

Name:            debug-tool
Version:         2.0.0
Health State:    normal
Health Status:   Addon Ready. For more info: http://ibm.biz/addon-state (H1500)

Note that that command syntax lines up with the syntax usage for other 'ibmcloud ks cluster' commands.

**Comment by derekpoindexter** [comment]
Thanks for the feedback. I've updated the example command. The change will be live soon.
