### ISSUE TITLE
Missing Satellite Documentation - Worker node encyption

### ISSUE THREAD

**Issue by ThomasUllrich666** [ibm-cloud-docs/containers#2686]
I miss a description how I can secure my on premises worker nodes. 
This section just explain how the VPC or Classis nodes are encrypted but not how I can encrypt Satellite nodes.
https://cloud.ibm.com/docs/containers?topic=containers-encryption#worker-node-encryption

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback.

Satellite is covered in the OpenShift documentation here - https://cloud.ibm.com/docs/openshift?topic=openshift-encryption#worker-node-encryption
