### ISSUE TITLE
Control plane encryption via Key Protect or Hyper Protect Crypto Services

### ISSUE THREAD

**Issue by ThomasUllrich666** [ibm-cloud-docs/containers#2687]
The table in this Documentation shows that the control plane can be encrypted via Key Protect or Hyper Protect Crypto Services but the section shows that the disks are encrypted via a IBM-managed key. https://cloud.ibm.com/docs/containers?topic=containers-encryption#control-plane-encryption

What is right? I didn't see a way to encrypt the Control plane disk via Key Protect or Hyper Protect Crypto Services

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback.

Encryption for the control plane is managed by IBM. I've updated the doc with the correct information.
