### ISSUE TITLE
Add info on API key reset best practice when specific user leaves the company

### ISSUE THREAD

**Issue by kmadhushree** [ibm-cloud-docs/containers#2688]
Content Needed Reason:
https://cloud.ibm.com/docs/containers?topic=containers-access-creds

API key for the cluster is derived from the region and resource group. The above document should have detailed explanation on how the api key of the cluster works and why a reset is needed when a user leaves the company. Every document that has the api key reset does not have the explanation on how it works and why it is needed which is important for the customers to understand. there are many cases for api key reset issue so its important to have the proper explanation in the document.
Example: case [CS4027955](https://watson.service-now.com/now/nav/ui/classic/params/target/sn_customerservice_case.do%3Fsysparm_query%3Dnumber%3DCS4027955)

[CS4036473](https://watson.service-now.com/now/nav/ui/classic/params/target/sn_customerservice_case.do%3Fsys_id%3D0f58cd35472f8610b9b4f46b416d43be%26sysparm_view%3Dcase%26sysparm_record_target%3Dsn_customerservice_case%26sysparm_record_row%3D27%26sysparm_record_rows%3D57%26sysparm_record_list%3Dsys_created_onONThis%2Bweek%2540javascript%253Ags.beginningOfThisWeek%2528%2529%2540javascript%253Ags.endOfThisWeek%2528%2529%255Eassignment_group%253D93b44b0b1b61a8146aebca262a4bcb01%255EconsumerISEMPTY%255EORDERBYDESCsys_created_on)

**Comment by mtreible-ibm** [comment]
Addressed and closed internally.
