### ISSUE TITLE
IBM Cloud CLI command is missing in example code

### ISSUE THREAD

**Issue by HeavyWombat** [ibm-cloud-docs/containers#2692]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/containers?topic=containers-ts-resource-group-permissions

### What do you think needs to be updated?

I believe that the code in step 2 of the How To Fix should be: `ibmcloud ks api-key info` based on the example below.
<img width="629" alt="image" src="https://github.com/user-attachments/assets/1e481cfe-d4af-4591-ae9f-1742f8d8d952">

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've updated the example commands. The changes will be live soon.
