### ISSUE TITLE
Understanding Secure by Default Cluster VPC Networking/Shared VPE gateway security group incomplete

### ISSUE THREAD

**Issue by petrandreev** [ibm-cloud-docs/containers#2694]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/containers?topic=containers-vpc-security-group-reference#vpc-sg-kube-vpegw-vpc-id
(same for [OpenShift](https://cloud.ibm.com/docs/openshift?topic=openshift-vpc-security-group-reference#vpc-sg-kube-vpegw-vpc-id))

### What do you think needs to be updated?

The very 1st paragraph is incomplete, see sentence(s) at the end of it:
`Shared VPE gateways might be added in later versions to allow connections to other IBM Cloud Services. For`

It is not clear - is something important missing after `For`?

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. I've updated the page. The change will be live soon.
