### ISSUE TITLE
Update the document with detailed Cgroup version change information for kubernetes version 1.29

### ISSUE THREAD

**Issue by dassou0** [ibm-cloud-docs/containers#2696]
### Which topic are you reporting about?

https://cloud.ibm.com/docs/containers?topic=containers-ubuntu-migrate.
https://cloud.ibm.com/docs/containers?topic=containers-changelog_129
https://cloud.ibm.com/docs/containers?topic=containers-cs_versions_129

### What do you think needs to be updated?

If migrating the IKS Worker Node from Ubuntu 20 to 24, the cgroup has been changed from v1 to v2, As mentioned in kubernetes docs and other cloud providers.

Kubernetes Docs
https://kubernetes.io/docs/concepts/architecture/cgroups/
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.29.md

AWS:
https://aws.amazon.com/jp/blogs/containers/amazon-eks-optimized-amazon-linux-2023-amis-now-available/
Azure:
https://github.com/Azure/AKS/blob/master/CHANGELOG.md#release-2024-03-17

**Comment by derekpoindexter** [comment]
Hi, thanks for the feedback. The doc update will be live soon
